### PR TITLE
new map replacements

### PR DESCRIPTION
**Pull request by Voros2**

### CODE REVIEW

**Comment by fragglet** [comment]
Please rename files to be all lowercase!

**Comment by Voros2** [comment]
The file extension too! Darn it. Coming right up.

**Comment by fragglet** [comment]
Thanks. Can you provide a bit of explanation about where these levels have come from? Did you make them all yourself, or are you submitting them on someone else's behalf?

**Comment by Voros2** [comment]
Didn't I? Well then: all the map replacements in Phase 2 are from Jayextee's Nex Credo mapset. The C1M2 map is made by YukiHerz.

**Comment by Voros2** [comment]
Closing this for now.

**Pull request closed without merging**
