### PR TITLE
Cwolf's new IoS sprite

### PR DESCRIPTION
**Pull request by Voros2**
Since Cwolf has apparently gone off into the army, id like to submit his sprite on behalf of him.

### CODE REVIEW

**Comment by fragglet** [comment]
We're getting rid of RMS? :(

**Comment by chungy** [comment]
Since the boss brain is only an insider joke (both in Doom and Freedoom), I don't think we ought to replace it with a serious sprite.

**Comment by Voros2** [comment]
But what if it becomes serious? The current IoS level is a clone of Doom 2's IoS level. It's not that impressive, ESPECIALLY now, where people have sourceports with mlook enabled. 
Sodaholic mentioned once that he would like to see a different IoS level:

The final level of phase 2 would take place inside this being and should be a completely different gimmick than raising a lift and shooting rockets. Perhaps have a series of switches you have to activate that temporarily expose the boss's weakpoint, and use the Keen actors as destructible shielding that you have to gradually widdle down to get to the Romero head.

**Comment by Voros2** [comment]
Quick test ingame:
http://m.imgur.com/TOk1WcH?r

**Comment by gamegenten** [comment]
I like this new one. I use the BossBrain actor on multiple levels and was going to replace the RMS head sooner than later.

**Comment by AXDOOMER** [comment]
That was a nice head replacement, but like John Romero's head, it's nothing serious. I wonder if RMS would agree to have his head on a sprite in a project distributed under the BSD license though. He's even the bad guy and you must kill him to win the game. I prefer the "serious" sprite.

**Pull request closed without merging**
