### PR TITLE
New Bronzes by Korp.

### PR DESCRIPTION
**Pull request by Xindage**
Improved Bronzes textures from freedoom by Korp.

Screenshot/comparison:
Old:
Screenshot_Doom_20210213_165841
Screenshot_Doom_20210213_165859
New:
Screenshot_Doom_20210213_165215
Screenshot_Doom_20210213_165541

### CODE REVIEW

**Comment by mc776** [comment]
Oof.

Looking at the two bottom screenshots it's really clear that the map had been designed for the old one. The bright high-contrast lines created by the new texture just makes everything look noisy and distracting for no good reason.

**Comment by Xindage** [comment]
Yes, i already mentioned him about it

**Comment by Talon1024** [comment]
I like the dark green and dark brown ones, but the bright brown ones are a bit too bright.

**Comment by Xindage** [comment]
ill contact korp regarding this bright bronze texture, if he has no plan in replacing it anytime soon i'll commit the dark brown and green wall alone since them actually looks cool.

**Comment by Calinou** [comment]
I do like the added contrast of the new orange bronze texture, but it needs to be darkened to match the original's *average* brightness.

**Comment by Xindage** [comment]
the original one has also 2 shades, orange and yellow, in certain pwads that's also used, so i'd like to retain that "feature" witch in the state right now wont allow me to do it. and it's too strong for the eyes.

**Comment by Xindage** [comment]
high contrast textures that korp was doing is not what he's targetting anymore, so i'll be closing it, until he know if he want to proceed with these edits or not.

**Pull request closed without merging**
