### PR TITLE
sprites: new floor light by Cascade

### PR DESCRIPTION
**Pull request by Talon1024**
This is from a WAD Cascade submitted on the Discord server

### CODE REVIEW

**Comment by mc776** [comment]
I retract my objections on Discord earlier, it's fine:
DOOM01
DOOM00

**Review by mc776 — APPROVED** [review]

**Comment by mc776** [comment]
That big splotch of uniform brown gets really distracting up close. I've darkened two pixels to break that up but I have no attachment to this particular method.
DOOM03
canda0-darkbrown

**Comment by mc776** [comment]
After looking at those screenshots I wanted to make one adjustment, which ended up being quite a few adjustments.

The big chunks of flat colours where the Doom palette clearly could afford to do more just looks off on an image this small, as well as the "light coming from the upper left" affecting *the light source itself*.

I've done a little bit more blending overall and made the light a bit less lopsided. If someone else would rather that the entire light be made symmetrical I'd be more than glad to do that:
canda0-darkbrown
DOOM00

**Review by mc776 — CHANGES_REQUESTED** [review]
(see comment)

**Comment by Cescade** [comment]
Acceptable change, never really given thought on the shadings of my 2nd reflections.

**Review by mc776 — APPROVED** [review]

**Pull request merged**
