### PR TITLE
New TNT DOSLVR textures

### PR DESCRIPTION
**Pull request by SenhorFlibble**
Here are DOSLVR animated texture sets that match TNT originals. The current patches are non-animated placeholders.

I based these on the old DOSHA placeholder texture -- apparently, someone started making at least DOSLVR2 patches but then used them as a basis for a placeholder instead.

### CODE REVIEW

**Comment by mc776** [comment]
I had just noticed these ones on TNT Map20 this morning!

**Comment by Xindage** [comment]
can you provide a gif or an ingame gif so we can see how it looks, the stationary images wont give us the idea of the animation.

**Comment by SenhorFlibble** [comment]
> can you provide a gif or an ingame gif so we can see how it looks, the stationary images wont give us the idea of the animation.

Here you go:
ezgif-4-46e5366e41

**Review by Xindage — APPROVED** [review]
good good.

**Pull request merged**
