### PR TITLE
Proluiz's patch fix

### PR DESCRIPTION
**Pull request by Voros2**
So there's some trouble with https://github.com/freedoom/freedoom/pull/317 and thus i made a new PR, with correct fixes to the GIFs.

wall78_1 made by Blastfrog 

yellow and wood by Proluiz

### CODE REVIEW

**Comment by Proluiz** [comment]
thanks, but few things:

1st, what was the issue whit the gifs?
2st, dont call me proluiz i hate this name i only use it because protox was already used by some user (call me protox only)

**Comment by Talon1024** [comment]
The WALL78_1 in this pull request is just an edited version of the Doom 2 texture, and it should not have been added.
Original WALL78_1 from Doom 2:
redwall
The new edited version:
aa8mm1a

**Comment by fragglet** [comment]
Thanks, filed #321 to address this.

**Comment by chungy** [comment]
Sodaholic... *sighs* I'm not all that surprised. Thanks for spotting it.

**Pull request closed without merging**
