### PR TITLE
Updated README How To Play with link to android Freedoom app

### PR DESCRIPTION
**Pull request by mkrupczak3**
Updated the README "How To Play" section with links to the [Freedoom android app GitHub page](https://github.com/mkrupczak3/GZDoom-Android) and the Delta Touch Google Play [store listing](https://play.google.com/store/apps/details?id=com.opentouchgaming.deltatouch)

### CODE REVIEW

**Comment by Calinou** [comment]
I haven't found the source code for Delta Touch anywhere online :disappointed:

**Comment by mkrupczak3** [comment]
I think the author of delta touch is [Emile Belanger](https://github.com/emileb), he goes by beloko  sometimes and is pretty active on Doomworld. He gives a free copy of Delta Touch to many people who ask on the forums. I own delta touch, and I may try to reach out to him at some point to get the source code for it. 

Regardless, Delta Touch is a newer port than the "Freedoom" for android fork I've been working on, so I thought it would be good to include both.

**Comment by mkrupczak3** [comment]
@chungy  any update?

**Comment by Calinou** [comment]
> Also (unrelated) @Calinou do you speak french? I'm looking for contributors for a translation of the Freedoom app: transifex.com/krupczakorg/freedoom-gzdoom/dashboard

Of course :smiley: I submitted some translation suggestions, could you accept them please?

**Comment by chungy** [comment]
While suggesting source ports is already something we do (on the web site and README both), we should not make recommendations for proprietary engines (I don't believe Delta Touch has ever had a source code release).

The "GZDoom-Android" repository might be okay to suggest, but we don't control its development and I can't say anything about its quality, and I would have deep concerns about that.

**Comment by mkrupczak3** [comment]
Hi @chungy, thanks for the reply.

I'm the maintainer for the freedoom android app (GZdoom android) and would like to vouch for its quality. It's a bit quirky and not as updated as d-touch but I think it's a great no-frills way to get people started playing with freedoom. I'm pretty sure I've had a few reviewers play through freedoom1 and freedoom2 without issues. I plan to add an idgames level browser soon to make playing wads easier.

You can check out the play listing here: https://play.google.com/store/apps/details?id=net.nullsum.freedoom&hl=en_US

The reviews are mostly positive, but the most common criticism is that it runs on an old version of GZDoom. I may do some refactoring at some point depending on how much this affects the project's ability to integrate with other communities.

**Comment by mkrupczak3** [comment]
Status?

**Comment by mkrupczak3** [comment]
Changed title: removed mention of Delta Touch as it is not fully GPL compliant

**Comment by chungy** [comment]
I apologize for the inactivity on the PR, but I have been uncomfortable with recommending a Freedoom port that is not under our control. I think you've done some good work, especially being on the play store, but I'll opt out of linking to it in the README file we have (that being said: I'd be more comfortable with linking it from our web site...)

**Comment by mkrupczak3** [comment]
@chungy taking another look at this since the new version of freedoom has come out. I'd like to transfer ownership of the android app to the freedoom community or someone who could take better care of it if you know of any.

It's been pretty popular and I think it's raised a lot of awareness for the freedoom project. I do think it has some quality and maintenance snags though, and would be willing to transfer it if it meant getting more contributors and eyes on it.

**Pull request closed without merging**
