### PR TITLE
New Phase1 Episode2 OST

### PR DESCRIPTION
**Pull request by KorpKat**
New midis for e2, packaged as a bundle so i dont have to keep making pull requests every time i finish one lol

### CODE REVIEW

**Comment by Calinou** [comment]
The files should be named in lowercase to replace the existing files.

**Comment by KorpKat** [comment]
> The files should be named in lowercase to replace the existing files. Right now, your branch contains the existing files in lowercase and the new files in uppercase.

oh shoot, is there a way to fix this somehow? i dont know how to use github :P

**Comment by mc776** [comment]
When I made this mistake I ended up manually deleting all the old files and then renaming all the new ones, one at a time. Not fun.

Depending on your patience for this sort of thing (and whether you know how to "rebase" or whatever) it might be more efficient to re-do the fork+PR from scratch.

**Comment by selliott512** [comment]
Since I'm a maintainer with your permission I'd like to fix the filename case issue, get rid of the merge commit (that's no big deal, just a little confusing to look at) which I can then push to your fork. So you can know for sure I didn't mess anything up here's the SHA-1 of the nine files right now:
```
a02450ab1079b79ac411bab1d1314d3b4a999a17  musics/D_E2M1.mid
4c935d6c769ff76995fc3f1b33dd3afaed0d9e4b  musics/D_E2M2.mid
0f2faaf0cfe121421895d438636404c272fe4795  musics/D_E2M3.mid
f72e81b8bb952a604dfb710e651bfacddb185c18  musics/D_E2M4.mid
cf294f7da7e4135542f6b4c203fab8a52ebe0650  musics/D_E2M5.mid
18b63a4a1cf9e88521b82f7d07bb12e9f54d468c  musics/D_E2M6.mid
ef76355d1eca01080f442fa9c7226d5c06a6e87b  musics/D_E2M7.mid
e31b11a61a64ad97b813e1762d402ea04a10b661  musics/D_E2M8.mid
24b22666b560b7cf3f3dee9d0ea285c750704cc5  musics/D_VICTOR.mid
```
It will be the same when I'm done, but lower case.

**Comment by selliott512** [comment]
I went ahead and did it now. I doubt there was any objection, and can `git reset --hard ...` to the previous commit if you really don't want it (ask me how).

**Pull request merged**
