### PR TITLE
revised worm death

### PR DESCRIPTION
**Pull request by Voros2**
hexereticdoom made a worm death scene using red blood instead of the current orange blood.

It looks better and makes more sense really.

### CODE REVIEW

**Comment by fragglet** [comment]
You haven't committed this correctly - your commit adds new files rather than modifying the existing ones.

**Comment by Voros2** [comment]
Oh shit, i forgot that it should be lowercase.

I'll reupload it in a few hours.

**Comment by Voros2** [comment]
Fixed.

**Comment by fragglet** [comment]
When deleting files, you can delete them all in a single commit - you don't need to make a commit per file.

**Comment by Voros2** [comment]
I know, but I couldn't find the revert button for some reason :P, so I resorted to deleting them one by one. But at least it's fixed now.

**Comment by Voros2** [comment]
What about the crediting Hexereticdoom?

**Comment by fragglet** [comment]
Oh, you're right - can you submit another pull request to fix it?

**Comment by Voros2** [comment]
Yes I can, but I'll need to gather his information first. Until merge sajbear and Voros(:P), as given in another PR.

**Pull request merged**
