### PR TITLE
graphics: add widescreen variants as `*_WS` graphics.

### PR DESCRIPTION
**Pull request by elf-alchemist**
First time contributing.
Laying down initial foundation, hence draft.

### CODE REVIEW

**Comment by elf-alchemist** [comment]
As per the work @GeorgePieVG has done on #1437, it seems only appropriate to ditch having the wide assets built-in, and instead best to have them in the new-fangled `fd-extras.wad` file. Once their changes are upstream, I'll merge them back to mine and reconfigure the build system to include the wide graphics as replacements to the normal lumps on `fd-extras.wad`, instead of a set of new lumps on the IWADs.

**Comment by GeorgePieVG** [comment]
> As per the work @GeorgePieVG has done on #1437, it seems only appropriate to ditch having the wide assets built-in, and instead best to have them in the new-fangled `fd-extras.wad` file. Once their changes are upstream, I'll merge them back to mine and reconfigure the build system to include the wide graphics as replacements to the normal lumps on `fd-extras.wad`, instead of a set of new lumps on the IWADs.

I don't disagree with your approach either, but I think the spec for non-replacing widescreen graphics should be standardized first.

**Comment by elf-alchemist** [comment]
Looking at the NyanDoom repo #1442 there doesn't seem to anything still under active development as far as the non-replacing assets are concerned, I don't believe.

But at any rate, yeah I'm thinking it's more appropriate to keep the wide assets separate for the moment, unless others agree that it should be included on the IWAD itself, it's still an early moment for the non-relpacing graphics feature, and the vanilla 4000 lump limit remains dangerously close, as it stands.

**Comment by elf-alchemist** [comment]
> Why did you close this one?

By mistake. I was trying to update my fork's master branch, to prevent merge conflict issues, but wasn't familiar with GitHub specifically did it, so it was an accident. I'll reopen once I get the time to work on this one again.

**Pull request closed without merging**
