### PR TITLE
Fixed some textures

### PR DESCRIPTION
**Pull request by Proluiz**
Used some textures in data to fix few plutonia textures, also i dont know why it cant be merged automaticaly

### CODE REVIEW

**Comment by Voros2** [comment]
I recently sent in a fix for wall78_1 in https://github.com/freedoom/freedoom/pull/303 but it was only a small fix to remove that small white streak.

And you can't automatically merge your changes to freedoom:freedoom since you don't have push access.

**Comment by Proluiz** [comment]
about the merge i mean this error "This branch has conflicts that must be resolved"

**Comment by Voros2** [comment]
Oh that. Try to update your branch then make a new pull request.

**Comment by uhbooh** [comment]
Didn't sodaholic make a redwall patch? If he did you can merge that one instead.

**Comment by Voros2** [comment]
I think the redwall patch in this PR IS that patch made by Sodaholic.

But I feel like this isn't good? Is it good?

**Comment by uhbooh** [comment]
It's not, this is the one made by sodaholic
https://www.doomworld.com/vb/post/1676492

**Comment by Blastfrog** [comment]
What's wrong with my version of REDWALL?

**Comment by Proluiz** [comment]
is better i close it and reopen it whit the new redwall? (blastfrog redwall)

**Comment by Proluiz** [comment]
well i see no reason for that also, let i update myself.

**Pull request closed without merging**
