### PR TITLE
bos2 and boss sprites based on raymoohawks pestmeister

### PR DESCRIPTION
**Pull request by luckypunk**
Original graphics by raymoohawk: https://www.doomworld.com/vb/freedoom/70095-raymoohawks-sprite-edits/

Gitting for the first time. Be gentle.

### CODE REVIEW

**Comment by chungy** [comment]
Thanks. My only real complaint are the death frames. Turning into a large bright-red corpse feels inappropriate, otherwise this is excellent. :)

**Comment by luckypunk** [comment]
Raymoohawk's death animation was black and white. I lack the skills to do more than recolor them. I could try to make them darker some time, but don't hold your breath.

**Comment by chungy** [comment]
The scale of them is a problem too, but this is good nonetheless.

**Comment by luckypunk** [comment]
You should probably discuss this with raymoohawk, I just sprited (and recolored and mirrored) them.

I guess moving the heads down a bit, giving them bigger humps would help, but I don't even feel artistically up to that task.

**Pull request merged**
