### PR TITLE
Restore old E1M9 midi - It fits better

### PR DESCRIPTION
**Pull request by jadenquinn**
The new midi for E1M9 doesn't really fit the slot, maybe let's bring it back in another slot, or maybe even in FreeDM?

### CODE REVIEW

**Comment by mc776** [comment]
"Hidden Between Spades" works with this map pretty well in my view. What don't you think fits? (also: what map do you think it *would* fit - that might shed a bit more light on why.)

**Comment by Anonysussy** [comment]
I like the current E1M9 just fine, I didn't really like how the old E1M9 track has a random cutoffs mid song and overall on me it sounds a bit jank at times, and it doesn't really fit with the more current aesthetic freedoom was going for.

**Comment by jadenquinn** [comment]
> I like the current E1M9 just fine, I didn't really like how the old E1M9 track has a random cutoffs mid song and overall on me it sounds a bit jank at times, and it doesn't really fit with the more current aesthetic freedoom was going for, also didn't really see how this one fits any better.

Liking midis is beside the point. This is objective, and the current one doesn't fit. 
The current midi is jank with some soundfonts too, the tremolo specifically causes problems, it's just something that Korp himself seemed to do a lot, I've since shown him what this does to some midi synths, so he may or may not be using them less, not sure, but yea.

The old one doesn't fit a secret map, true, but it was E1M9 before. The current aesthetic Freedoom is right now is completely disjointed, objectively, so that's not a good metric.

I have no idea what you mean by random cutoffs mid song, I've used 6 different midi synths with this song, and GarageBand too, and none of those exhibited that. If you could explain what you mean by this, and when they happen, I'd look into it. Maybe that could be fixed if that's an issue.

**Comment by jadenquinn** [comment]
> "Hidden Between Spades" works with this map pretty well in my view. What don't you think fits? (also: what map do you think it _would_ fit - that might shed a bit more light on why.)

It's less about it fitting, and more about it causing problems with midi synths that make it sound like garbage. Maybe if this wasn't a problem, it wouldn't need to be replaced. The aforementioned tremolo, it immediately starts.

**Comment by Anonysussy** [comment]
> > I like the current E1M9 just fine, I didn't really like how the old E1M9 track has a random cutoffs mid song and overall on me it sounds a bit jank at times, and it doesn't really fit with the more current aesthetic freedoom was going for, also didn't really see how this one fits any better.
> 
> Liking midis is beside the point. This is objective, and the current one doesn't fit. The current midi is jank with some soundfonts too, the tremolo specifically causes problems, it's just something that Korp himself seemed to do a lot, I've since shown him what this does to some midi synths, so he may or may not be using them less, not sure, but yea.
> 
> The old one doesn't fit a secret map, true, but it was E1M9 before. The current aesthetic Freedoom is right now is completely disjointed, objectively, so that's not a good metric.
> 
> I have no idea what you mean by random cutoffs mid song, I've used 6 different midi synths with this song, and GarageBand too, and none of those exhibited that. If you could explain what you mean by this, and when they happen, I'd look into it. Maybe that could be fixed if that's an issue.

I just recently relistened to it, apparently the sound cutoffs was a bug on VLC player where when I try to skip to a certain part of the song it broke the soundfont I used (the SC-55 one) or it probably reset my soundfont to the android default, so that's part of my problem.

**Comment by jadenquinn** [comment]
> > > I like the current E1M9 just fine, I didn't really like how the old E1M9 track has a random cutoffs mid song and overall on me it sounds a bit jank at times, and it doesn't really fit with the more current aesthetic freedoom was going for, also didn't really see how this one fits any better.
> > 
> > 
> > Liking midis is beside the point. This is objective, and the current one doesn't fit. The current midi is jank with some soundfonts too, the tremolo specifically causes problems, it's just something that Korp himself seemed to do a lot, I've since shown him what this does to some midi synths, so he may or may not be using them less, not sure, but yea.
> > The old one doesn't fit a secret map, true, but it was E1M9 before. The current aesthetic Freedoom is right now is completely disjointed, objectively, so that's not a good metric.
> > I have no idea what you mean by random cutoffs mid song, I've used 6 different midi synths with this song, and GarageBand too, and none of those exhibited that. If you could explain what you mean by this, and when they happen, I'd look into it. Maybe that could be fixed if that's an issue.
> 
> I just recently relistened to it, apparently the sound cutoffs was a bug on VLC player where when I try to skip to a certain part of the song it broke the soundfont I used (the SC-55 one) or it probably reset my soundfont to the android default, so that's melery part of my problem.

That's VLC's problem. I've never gotten anything to play through that correctly, it always sounds really off, either it adds reverb, doubles the instruments for no reason, or just doesn't play half of the notes or instruments, it seems really buggy and seems like they added it as an afterthought. Please don't.. use VLC for this.. just put whatever midi in a WAD with D_E1M1 as the lump name, save, and open that in GZDoom and use whatever soundfont through GZDoom to play it, it'll be much better, however less flexible in terms of saving the music, that's the tradeoff. Alternate players include Foobar2000, which is what I use when it's not just as buggy as VLC to skip around in a song, but if I want to hear the midi played correctly and not off at all, I'll just use the aforementioned GZDoom WAD playback method.

**Comment by Josephus-DH4050-Astartes** [comment]
yeah. I was upset when Raging Sun was booted xD

**Comment by Josephus-DH4050-Astartes** [comment]
besides, Freedoom would benefit with more metal music.

**Comment by Josephus-DH4050-Astartes** [comment]
eh that's fine, my reimagining is way darker anyway lol, so my version uses industrial metal and cathedral power metal, but what i'm trying to say is, freedoom feels better with heavier music, maybe synth hard rock or smth.

**Comment by KorpKat** [comment]
> eh that's fine, my reimagining is way darker anyway lol, so my version uses industrial metal and cathedral power metal, but what i'm trying to say is, freedoom feels better with heavier music, maybe synth hard rock or smth.

i beg to differ, thought I'm probably biased i really enjoy Lola's contributions and feel it should be the "standard" in style/genre new contributors should lean on to score maps. Much more because of consistency too, as it would be kind of awkwardly to have a lot of very harmonically fun guitar riffs, synthesizer pads and lead solos only to out of nowhere have a random grungy heavy piece.

**Comment by Josephus-DH4050-Astartes** [comment]
I love her Episode 3 scores. They seem alot more power metal than the rest of the game, thats why in phase 2, when I get to cluster 3, I just atart turning on some Powerwolf xD

**Comment by jadenquinn** [comment]
Lola should do an E1M9 specific track. Screw ones that are already in, we need some new great stuff.

**Comment by jadenquinn** [comment]
Closing on grounds that I agree with some points people made in here, and would like to say that Lola should make a new E1M9 track. She's never disappointed me, and I feel that a lot of you feel the same way about her tracks. I think we just need some new stuff.

**Pull request closed without merging**
