### PR TITLE
patches: new WALL25_1 by Korp.

### PR DESCRIPTION
**Pull request by mc776**

### CODE REVIEW

**Comment by Calinou** [comment]
This will trigger trypophobia for sure, but I like it nonetheless :smile:

**Comment by axredneck** [comment]
It is horror FPS after all, it's supposed to be creepy.

**Comment by mc776** [comment]
In all seriousness though that was one of the reasons why I hadn't posted this PR much earlier.

So far everyone mentioning it seems to just be bringing this up theoretically but has it actually affected anyone?

**Review by Xindage — APPROVED** [review]
Committing

**Pull request merged**
