### PR TITLE
patches: removed orange pixel from w106_1 & w107_1

### PR DESCRIPTION
**Pull request by luckypunk**
https://www.doomworld.com/vb/post/1720376

### CODE REVIEW

**Comment by Voros2** [comment]
Shouldn't Litrivin be credited?

**Comment by luckypunk** [comment]
I think "patches: removed orange pixel from w106_1 by Litrivin" and linking to his comment should count as credit. What am I missing?

**Comment by Voros2** [comment]
As in editing the CREDITS file on the freedoom repo, to include Litrivin and his/her info.

**Comment by luckypunk** [comment]
Then yes, (s)he should get credit.

**Comment by chungy** [comment]
Can you please clean up your branch so that only the relevant changes are included?

**Comment by luckypunk** [comment]
There are only two files included, both are relevant.

If you are talking about the commit messages, they come from my master branch. If you know how to get rid of them, please tell me.

**Comment by chungy** [comment]
Use `git rebase -i`

**Pull request closed without merging**
