### PR TITLE
Use Korp's pistol offsets.

### PR DESCRIPTION
**Pull request by unithecutie**
(might get closed immediately like #1172) 

Reminder that this is a 90's-style game, not a realism shooter - the "no one shoots like that" argument from the Discord discussion about this shouldn't apply. Feedback is more important than realism here.

Also this:
image

### CODE REVIEW

**Comment by MerrittK** [comment]
The github can't be a tug-of war between MC776 and everyone else. It isn't healthy for the community,

**Comment by MerrittK** [comment]
Also, the comments have been getting gradually more dismissive and rude, for everyone.

**Comment by mc776** [comment]
If the other maintainers want me removed I will defer to them.

**Comment by mc776** [comment]
Unlocking this with my apology.

I've finally managed to talk about this (both the merits of the proposed change itself and the social dynamic going on here) with a couple people whose judgment I trust. Yes I am being unreasonable here - this has evolved in my head into something not unlike one of those things where you've got five siblings who've nearly settled their year-long estate lawsuit and then someone mentions they need to decide where to put dad's urn and 5 minutes later everyone's getting ready for trial again.

@unithecutie if you repost I'll merge it, but I would like to suggest folks try one alternative first:
```
PISFA0  -144    -75
PISGA0  -125    -86
PISGB0  -125    -89
PISGC0  -124    -91
PISGD0  -125    -84        ; Unused
PISGE0  -123    -80        ; Unused
```

**Comment by mc776** [comment]
does this reopen and comment button do anything

**Review by mc776 — APPROVED** [review]

**Comment by unithecutie** [comment]
I'll test your alternative out, just waiting for it to build.

**Comment by mc776** [comment]
> but I would like to suggest folks try one alternative first:
> 
> ```
> PISFA0  -144    -75
> PISGA0  -125    -86
> PISGB0  -125    -89
> PISGC0  -124    -91
> PISGD0  -125    -84        ; Unused
> PISGE0  -123    -80        ; Unused
> ```

^^^ PR approved but leaving this open for a bit

**Comment by MerrittK** [comment]
Thanks for giving Korp's offsets another shot.

**Comment by unithecutie** [comment]
The alternative is certainly a lot better than the current one, but it still feels a bit too stiff.

**Comment by mc776** [comment]
> but it still feels a bit too stiff

Just to be clear: the one thing that swayed me was someone pointing out that the erratic jerking motion was in fact appropriate and looked better in representing someone who was firing quickly *while on the run* as is typical in Doom gameplay, and I simply never notice this because either I'm stopping to aim at a distant target or I'm not looking at the weapon sprite at all.

If all the input I had was what has been leveled at me here before my initial reply, this would never have been reopened.

**Pull request merged**
