### PR TITLE
More level tweaks

### PR DESCRIPTION
**Pull request by Talon1024**
Check the commit messages for more details.

### CODE REVIEW

**Comment by Voros2** [comment]
By the way, are you aware of Gothic's MAP30 submission? People have agreed to split it into two maps as MAP29 and MAP30, and possibly move the current MAP29 to slot 32.

https://www.doomworld.com/forum/topic/93596-map30-submission-devils-core/

**Comment by Talon1024** [comment]
IIRC people were talking about replacing the WolfSS with an enemy from Shadow of the Wool Ball, and using a Shadow of the Wool Ball-themed level for MAP32.

On the other hand, the MAP26 slot is open.

**Comment by Voros2** [comment]
Yes, you're right about that, although nothing ever really happened on that matter. No legible textures, sprites or maps were made regarding a SotWB secret.

MAP26? There's really nothing to do on that matter unless someone has a map to contribute or would like to move a map to this slot. The old MAP18 might make for a suitable replacement but it needs retexturing and possibly a layout/design change. 

MAP27 needs to be ditched, if you ask me. I don't think anyone liked this one-hour-long map.

**Comment by NickZ** [comment]
Was there anything left to do on this PR? Is this ready to merge?

**Comment by Talon1024** [comment]
I think it's ready to merge. These aren't significant changes to the levels. I'd rather do a separate pull request for such changes.

**Pull request merged**
