### PR TITLE
Potential MAP20 replacement

### PR DESCRIPTION
**Pull request by Tiramisu100**
I made a potential replacement for MAP20.

Arguments for:
- Better visuals and fights
- Maintains the overall idea and certain elements of previous version
- Fits the potential new lore (see #1402) of being built over AGM headquarters

Arguments against:
- Labyrinthine and potentially confusing layout
- Pushes drawseg limits

I am open to feedback, although if the proposed changes end up being too extensive then I would rather withdraw the level instead (which is fine by me too, so please don't feel pressured).

### CODE REVIEW

**Comment by mc776** [comment]
> Labyrinthine and potentially confusing layout

Did a first run on chocolate in god mode in medium skill, got through in just over 16 minutes. I might have used the automap once but only to try to get out of the lava pit (the one with the invuln sphere).

The way to each key got a little confusing in a few places until I started to recognize where I had or had not been.

I don't think it's noticeably worse than most current Freedoom maps in this regard.

**Comment by mc776** [comment]
Since this is a brand new map I think it should have a new name.

**Comment by Anonysussy** [comment]
I'd recall testing this one out on Chocorenderlimits and there's a HOM effect, it doesn't crash though, just came off as a bit of a suggestion to work things around a bit.

**Comment by Tiramisu100** [comment]
> Did a first run on chocolate in god mode in medium skill, got through in just over 16 minutes. I might have used the automap once but only to try to get out of the lava pit (the one with the invuln sphere).

That's good to hear, 16 minutes sounds about right for a first run! As for the lava pit, I think I'll just add another entrance to the structure at the front, to make it clear it's the "main path" there.

> Since this is a brand new map I think it should have a new name.

I personally really like the name "Blood Ember Fortress" so I won't be coming up with anything else, but if you want to then feel free to change the name later on.

> I'd recall testing this one out on Chocorenderlimits and there's a HOM effect, it doesn't crash though, just came off as a bit of a suggestion to work things around a bit.

Oh, I thought I dealt with them all at this point - I'll take another look then.

**Comment by Anonysussy** [comment]
> Oh, I thought I dealt with them all at this point - I'll take another look then.

I'd recall it isn't quite visible and pretty easy to miss but it's detected on CRL, so I thought of mentioning that.

**Comment by Tiramisu100** [comment]
Due to irl circumstances I don't think I will actually be able to provide fixes and maintenance for this map in the near future, so I'm closing this PR - but if anyone wants to take it from here then feel free to edit it as needed and open another one (you can link to this PR to preserve the feedback that's already there). If any of my contributions end up getting included in the project then I do not wish to be publicly credited for them.

**Pull request closed without merging**
