### PR TITLE
graphics: offset M_PAUSE X by -8.

### LINKED ISSUE #1153: M_PAUSE off center
Doom's source code has a hard coded width value for the pause graphic of 68 pixels. Freedoom's is only 52 pixels wide.

### PR DESCRIPTION
**Pull request by mc776**
Closes #1153.

### CODE REVIEW

**Comment by selliott512** [comment]
Would you mind clarifying where this is? In PrBoom+ the keybinding setup menu looks like this before and after this change for me:

pause-menu

**Comment by unithecutie** [comment]
image
Top of the screen when you use said function.

**Comment by selliott512** [comment]
Thanks for the explanation. I don't normally use that feature, but still seems like I should've tried it in hindsight.

That being said it seems like this change makes the "PAUSE" less centered for PrBoom+. Here are before and after screenshots imported into The Gimp with vertical guidelines added, demonstrating that it was centered around the pistol before, but not after:

before:
pause-before-guidelines

after:
pause-after-guidelines

Averaging the guideline coordinates gives the center of the word in both cases:
```
  before: (844 + 1076) / 2 = 960
  after : (880 + 1114) / 2 = 997
```
The before value of 960 is exactly the center of my 1920 width monitor. Am I missing something? Do different engines behave differently?

**Comment by mc776** [comment]
So PRBoom+ dynamically centers the pause graphic unlike vanilla?

**Comment by mc776** [comment]
I just gave it a try on Crispy. It behaves the same as vanilla.

If we have to fix this with a larger graphic I'd like to see something clearly visually distinct from the regular fonts, just in case that stuff gets updated...

**Comment by mc776** [comment]
I'll post a new PR with fawtytoo's spaced lettering.

**Comment by selliott512** [comment]
I don't know if it is helpful, but the "PAUSE" is centered before and after this now closed PR in GZDoom.

**Pull request closed without merging**
