### PR TITLE
New E2M8 map

### PR DESCRIPTION
**Pull request by Anonysussy**
Split the E2M8 PR from the ENDOOMs, closing #1385.

### CODE REVIEW

**Comment by Anonysussy** [comment]
Just tested this one, it got HOMs, gonna reedit this one.

**Review by Xindage — CHANGES_REQUESTED** [review]
ok i tried this and no... 2 cyberdemons and you give me just rockets...

There's 3 things that i need to be changed if you wanna this to happen.
1 - Dont allow players to go inside the portal from where they came from, just to keep the consistence between the maps from that episode.
2 - Weapon variety please.
3 - Make the cybers capable of navigating around to chase the player, at least on my game they never leave his area to chase the player, not sure if you used monster blocking lines of if they're just plain stuck.

**Comment by Anonysussy** [comment]
> ok i tried this and no... 2 cyberdemons and you give me just rockets...
> 
> There's 3 things that i need to be changed if you wanna this to happen. 1 - Dont allow players to go inside the portal from where they came from, just to keep the consistence between the maps from that episode. 2 - Weapon variety please. 3 - Make the cybers capable of navigating around to chase the player, at least on my game they never leave his area to chase the player, not sure if you used monster blocking lines of if they're just plain stuck.

Gonna work on those, btw I never used any monster blocking lines, ig it's either map structure or the wall, gonna try and remove those if possible, also the rockets were mostly done because both plasma and BFG could easily shred through the boss while shotgun and chaingun is pretty useless and could only be used as a last resort, though plasma gun could probably work out as a part of the teleporting puzzle (requiring player to use the teleporters around as a means to get better weapon).

**Comment by Anonysussy** [comment]
Closed this one, this one is quite unpolished of a map.

**Pull request closed without merging**
