### PR TITLE
Replace DM22 with another map and move old DM22 to DM32

### PR DESCRIPTION
**Pull request by AXDOOMER**
~~DM22 was marked as a map to be replaced~~
 
~~DM32 is now to be replaced~~

Read the PR's title.

### CODE REVIEW

**Comment by Xindage** [comment]
Screenshots would be nice.

**Comment by AXDOOMER** [comment]
Here are a few
image
image
image

**Comment by AXDOOMER** [comment]
@Xindage An update on this would be appreciated.

**Comment by Xindage** [comment]
plan is to put it inside my own PR, right now i'm experimenting a new git tool so i'm taking slow steps at time, and i haven't figured how to inherit someone else repo/PR, so i can manually merge your commit in my PR.

**Comment by AXDOOMER** [comment]
It seems like a weird way to do it and error prone. What would this achieve? What are the benefits? 

You'd have to take my commits and apply them to your branch. It seems like an inefficient way of using Github and its PR mechanism. 

In my opinion, changes that are ready to be released should be merged as soon as possible so that players can test them. This also enables you to receive quicker feedback because people don't play the out-of-tree version of the maps. 

I assume you'd want to move this change inside https://github.com/freedoom/freedoom/pull/720, although this PR has been opened for more than a year and I'm sure some of those maps contain fixes that would be ready to be merged. Using different PRs for each map means you're not blocking a map because some other map is not ready to be merged. Merging them all at the same time means you have to wait and that players have to wait longer before they can enjoy the improvement that have been made to these maps.

**Comment by Xindage** [comment]
well merging that right now on the master branch of freedoom is really wanting to not be tested, because when I do the freedm servers in tspg i have to ensure that everyone has the same assets present in the PWAD not in the IWAD, you ask why? look here every time when i used to host the server i get people complaining "hey i have missing textures" or suddenly someone get kicked from the server because incorrect iwad mismatch, so what i was my idea, i set the server as not pure (SV_PURE 0) this allow players to not be kicked but wont solve the textures and map mismatch that's when my unfinished PR enter the thing, i generate a PWAD using the content from my branch creating the wad that make the server stable and it replaces ALL maps from the IWAD, so if i add your map in the master it'll be replaced by my branch during the online tests, because i must ensure that all maps are the same regardless of the IWAD used, for example you can use also doom2 in the server if you want it wont matter if the map differ the pwad fix it and replaces all the textures too that's why i need to merge your PR in my branch, it's to allow it to appear when i do the online plays in TSPG.

**Comment by AXDOOMER** [comment]
I understand, but merging this in master doesn't prevent you from also adding the map to your custom PWAD. It makes no sense for other players who like to use the bleeding edge builds of FreeDM (such as myself). I personally don't have the time to build a custom PWAD and adding out of tree maps to new network games (e.g. when starting a new server on Chocolate-Doom) is cumbersome (every other players must also add each map manually). I'm actually more prone to experiencing the errors that you're having such as WAD mismatches because this is not merged in master.

**Comment by mc776** [comment]
I don't normally play much Doom DM, but I just took a quick look at the current DM22 and this map and I really like both - Fourplay looks like it'd be a blast for some mods or games with more players.

Could this replace Map32 instead? (Or perhaps Fourplay can replace Map32 and Mildepot can go to 22?)

**Comment by AXDOOMER** [comment]
I think the reason Xindage elected for DM22 to be replaced is because of its symmetry and the fact that it was very large. Symmetric maps are not that interesting and the fact that it's large means it's less fast-paced, even worse in two player matches. 

This PR is very old and I hope something will be done about it soon. It's probably still waiting on https://github.com/freedoom/freedoom/pull/720 , but Xindage never invited me to a test match with all the new maps and this map included like he said he would.

**Comment by mc776** [comment]
At this point there's an irreconcilable conflict in the PR.

And we've still got that stupid mushroom map for Map32.

If you can re-post the PR with the updated credits and dehacked, and move the current Map22 to replace the current Map32 (and update the dehacked accordingly so the names match), I'd be more than happy to merge it.

**Comment by AXDOOMER** [comment]
Ok then. What's the Map32 easter egg? Looks like Chocolate, but I don't believe I understand the reference.

**Comment by AXDOOMER** [comment]
Here we go @mc776 

Thanks for unblocking this

**Comment by AXDOOMER** [comment]
I misunderstood you and did the wrong thing, it's fixed now. 

DM22 (Fourplay) moved to DM32 (Chocolate). Chocolate is thus removed.

This new map is now DM22.

**Review by mc776 — APPROVED** [review]

**Comment by mc776** [comment]
> What's the Map32 easter egg? Looks like Chocolate, but I don't believe I understand the reference.

If you turn on the automap in the map "Chocolate" it looks like the Mario 1UP mushroom.

The map itself and the music is not Mario-like in any way whatsoever.

**Pull request merged**
