### PR TITLE
New sprites for Summoner and Dead Flare

### PR DESCRIPTION
**Pull request by HorroMovieGuy**
New monster sprites by Korp and HorrorMovieRei. New summoner which we dubbed "Matribite" due to it being based on the Trilobite, and a new Dead Flare replacement named "hatchling" since it is some sort of larvae.

Included is also a tinkered version of the death sound made by mc776 so it synchs better with the new death animation for the Matribite.

### CODE REVIEW

**Comment by mc776** [comment]
Thoughts about adding that dssklatk to this PR as well? https://discord.com/channels/616148111076884520/692859569189290015/881324760871620648

**Comment by HorroMovieGuy** [comment]
> Thoughts about adding that dssklatk to this PR as well? https://discord.com/channels/616148111076884520/692859569189290015/881324760871620648

done 👍

**Comment by Talon1024** [comment]
You can change the names of the monsters by editing Freedoom's DEHACKED file: https://github.com/freedoom/freedoom/blob/060aa0492de0200bbac1bc41f07beb6b8e9c27aa/lumps/dehacked/dehacked.txt#L241

**Comment by selliott512** [comment]
I really like the new monsters. Very creative. Freedoom's own unique monsters.

Maybe the hatching charge sound is a bit loud. I tried halving the volume:
```
cd sounds && sox -v 0.5 dssklatk.wav out.wav && mv out.wav dssklatk.wav
```

**Comment by selliott512** [comment]
Also, when and if you update the names there's also the manual:
```
git grep -iP 'summoner|deadflare'
lumps/dehacked/dehacked.txt:CC_LOST = deadflare
lumps/dehacked/dehacked.txt:CC_PAIN = summoner
lumps/dehacked/dehacked.txt:OB_SKULL=%o was slammed by a deadflare.
manual/manual.adoc:| **Deadflare** |
manual/manual.adoc:image:images/monster-deadflare.png[Deadflare,100,100]
manual/manual.adoc:| **Summoner** |
manual/manual.adoc:These mobile Deadflare production factories will ensure you always have more
manual/manual.adoc:image:images/monster-summoner.png[Summoner,100,100]
```

**Comment by mc776** [comment]
> I really like the new monsters. Very creative. Freedoom's own unique monsters.
> 
> Maybe the hatching charge sound is a bit loud. I tried halving the volume:
> 
> ```
> cd sounds && sox -v 0.5 dssklatk.wav out.wav && mv out.wav dssklatk.wav
> ```

how's this? https://discord.com/channels/616148111076884520/692859569189290015/881629608389263462

**Comment by HorroMovieGuy** [comment]
The sound has been replaced with the revised version, so it's not too loud now. Went ahead and changed the dehacked, and manual information as well while I was at it. I changed the pictures and slightly altered the descriptions too if that's alright.

**Comment by mc776** [comment]
One tiny editorial thing: "charges" since we're using singular now

**Comment by HorroMovieGuy** [comment]
> One tiny editorial thing: "charges" since we're using singular now

Woops, that was a typo, I meant to write "larvae". I think referring to this monster in plural form is more fitting, since it's a swarm-type enemy.

**Comment by selliott512** [comment]
Good job. I like the manual descriptions and pictures. The only remaining small problem I see is that the `.PNG` suffix is upper case for the manual images:
```
manual/images/monster-hatchling.PNG
manual/images/monster-matribite.PNG
```
It's not just a matter of convention, upper case causes a bit of git confusion since `.gitattributes` only lists the lower case version:
```
...
*.png -text
...
```
So it thinks the nature of the file has changed.

**Comment by HorroMovieGuy** [comment]
> The only remaining small problem I see is that the `.PNG` suffix is upper case for the manual images

I had to go through some hoops but it should be fixed now, as they show as lowercase in the file list. Glad to know about this peculiarity for future PRs though.

**Pull request merged**
