### PR TITLE
Shorten DSCYBSIT (assault tripod wakeup sound)

### PR DESCRIPTION
**Pull request by KukoBerry**
Self-explanatory title. Only made sound slightly faster and cut some low-volume parts in the beginning and end.

### CODE REVIEW

**Comment by Xindage** [comment]
ok i check and its better still i cant PR it since it failed, maybe something is not right.

**Comment by GeorgePieVG** [comment]
Converting the sound to Doom format and back to wav via SLADE3 fixes the issue

**Comment by KukoBerry** [comment]
on it! thank you for the guidance

**Comment by KukoBerry** [comment]
Just commenting here that the file's already fixed, and it can be PR'd now @Xindage

**Review by Xindage — APPROVED** [review]

**Pull request merged**
