### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by Voros2**
Jewellds' new Freedoom title logo.

Replaces m_doom.gif

### CODE REVIEW

**Comment by Voros2** [comment]
I doubt the offset will have to changed for this to work properly.

**Comment by CraftedPixel** [comment]
I like the original because it looks more 3D. Also, your logo doesn't fit with the dimensions correctly.

**Comment by Voros2** [comment]
I'll provide the offset values then.

But I won't unless the pistol gets merged/rejected again.

**Comment by fragglet** [comment]
Looks good. It's better to use this as it's less Doom-esque. Also matches the FreeDM logo which is nice.

**Pull request merged**
