### PR TITLE
levels: fix some E1M2 aesthetics.

### LINKED ISSUE #1245: Improve E1M2 doortrak.
C1M1_001

As you move towards it, or backwards from it, it really "strobes", with the lines becoming wider and thinner:
C1M1_002

_Originally posted by @dftf-stu in https://github.com/freedoom/freedoom/issues/1240#issuecomment-1862870735_

### PR DESCRIPTION
**Pull request by mc776**
Closes #1245.

Fix that bridge to look a little less awkward and #996-compliant.

Add a decorative door to the starting area monster closet, implying the monsters are coming in from another, inaccessible part of the facility. It does, however, make the floor match the main area again.

Make the freestanding AGM logo bolder, simpler and stronger.

Adjust some textures in and near the big skylight hall to lean into the quasi-outdoors aesthetic while also replacing the grate floor textures with something a bit easier on the eyes in low-res.

### CODE REVIEW

**Comment by MerrittK** [comment]
Could the pull request come with some screenshots?

**Comment by mc776** [comment]
DOOM04
DOOM03
DOOM02
DOOM01
DOOM00
DOOM06
DOOM05

**Review by selliott512 — APPROVED** [review]
Looks good. I played it UV-MAX no problem. The aesthetic changes in the starting room look nice to me, but I haven't compared the other aesthetic changes carefully.

One small thing - Eureka doesn't like that the ceiling is below the floor for sector 332. So if you could raise it from 98 to 100, which doesn't seem to be visible, it would make Eureka happy.

**Comment by mc776** [comment]
Turns out that sector wasn't even needed with the simpler geometry.

**Pull request merged**
