### PR TITLE
patches: new and updated TNT/Plutonia textures

### PR DESCRIPTION
**Pull request by Talon1024**
Check the commit messages to see what resource(s) each image is based on.

Also, check out these links for preview WADs, and check out the custom texture thread on ZDoom forums for the source images, and truecolour versions of these textures:
[New textures](http://www.ciinet.org/kevin/myimages2/doom/freedoom/newpchs.wad) (Updated 2017-07-11)
[Alternatives](http://www.ciinet.org/kevin/myimages2/doom/freedoom/newpchs2.wad)

### Resource Library ###

[Truecolour BRBRICK2](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/brbrick2.png)
[Truecolour BRBRICK](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/brbrick.png)
[Truecolour BRICK1](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/brick1.png)
[Truecolour BRICK2](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/brick2.png)
[Truecolour BRICK](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/brick.png)
[Truecolour BROCK2 alternative](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/brock2a.png)
[Truecolour BROCK2](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/brock2.png)
[Truecolour BROWN1](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/brown1.png)
[Truecolour old BROWN2](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/brown2_1.png)
[Truecolour BROWN2](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/brown2.png)
[Truecolour BROWN3](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/brown3.png)
[Truecolour BROWN5](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/brown5.png)
[Truecolour CONCRETE](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/concrete.png)
[Truecolour DARKROCK](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/darkrock.png)
[Truecolour DIRBRI1](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/dirbri1.png)
[Truecolour DIRBRI2](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/dirbri2.png)
[Truecolour DORED](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/dored3.png)
[Truecolour MARBLE1](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/marble1.png)
[Truecolour MOSSBRIK](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/mossbrik.png)
[Truecolour MUD](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/mud.png)
[Truecolour MYWOOD](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/mywood2.png)
[Truecolour NATROCK](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/natrock.png)
[Truecolour gray REDROCK](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/redrock.png)
[Truecolour TILE alternative](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/tile2.png)
[Truecolour TILE](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/f/tile.png)
[**ZDoom forums post containing all of the above textures**](https://forum.zdoom.org/viewtopic.php?f=37&t=31139&p=989287#p989287)

[Truecolour ROCK without depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/Rock.png)
[Truecolour ROCK with depth and subtle cracks](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/RockB.png)
[Truecolour ROCK with depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/RockC.png)
[Truecolour MOSSROCK without depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/MossRock.png)
[Truecolour MOSSROCK with depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/MossRockB.png)
[Truecolour bright MOSROK2 without depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/MosRok2.png)
[Truecolour bright MOSROK2 with depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/MosRok2a.png)
[Truecolour dim MOSROK2 without depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/MosRok2b.png)
[Truecolour dim MOSROK2 with depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/MosRok2c.png)
[Truecolour MOULD](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/mould3.png)
[Truecolour FIREBLU1 (frame 1) with depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/fireblu1.png)
[Truecolour AROCK2 (frame 2) with depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/arock2.png)
[Truecolour AROCK3 (frame 3) with depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/arock3.png)
[Truecolour AROCK4 (frame 4) with depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/arock4.png)
[Truecolour AROCK5 (frame 5) with depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/arock5.png)
[Truecolour FIREBLU2 (frame 6) with depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/fireblu2.png)
[Truecolour FIREBLU1 (frame 1) without depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/fireblu1a.png)
[Truecolour AROCK2 (frame 2) without depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/arock2a.png)
[Truecolour AROCK3 (frame 3) without depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/arock3a.png)
[Truecolour AROCK4 (frame 4) without depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/arock4a.png)
[Truecolour AROCK5 (frame 5) without depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/arock5a.png)
[Truecolour FIREBLU2 (frame 6) without depth](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/fireblu2a.png)
[Truecolour MC1/MC20](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/mc1.png)
[Truecolour MC2/MC19](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/mc2.png)
[Truecolour MC3/MC18](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/mc3.png)
[Truecolour MC4/MC17](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/mc4.png)
[Truecolour MC5/MC16](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/mc5.png)
[Truecolour MC6/MC15](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/mc6.png)
[Truecolour MC7/MC14](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/mc7.png)
[Truecolour MC8/MC13](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/mc8.png)
[Truecolour MC10/MC11/MC12](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/mc10.png)
[**ZDoom forums post containing all of the above textures**](https://forum.zdoom.org/viewtopic.php?f=37&t=31139&p=994437#p994437)

[Truecolour DOPUNK4](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/dopunk4_2.png)
[DOPUNK4 source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/dopunk4_2src.png)
[Rock bumpmap](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/Rockdispl128.png)
[Rock bumpmap (1024x1024)](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/Rockdispl.png)
[Inverted rock bumpmap](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/Rockdispl128a.png)
[Edited rock bumpmap](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/Rockdispl128b.png)
[**ZDoom forums post containing all of the above textures**](https://forum.zdoom.org/viewtopic.php?f=37&t=31139&p=993589#p993589)

[Moss source image (MOSSBRIK, MC, FIREBLU/AROCK, MOSSROCK, MOSROK2, BRBRICK2, BROWN1, BROWN5)](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/mossbase.png)
[Ununsed source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/miscrock.png)
[Source image for CONCRETE, BRICK1, PSTON2, and MUD](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/miscrock2.png)
[Source image for BRICK, BRICK2, MOSSBRIK, MOSROK2, AROCK/FIREBLU, ROCK, MOSSROCK, DIRBRI1, DIRBRI2, BROCK2, BRBRICK (displacement), BRBRICK2 (displacement)](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/Pluroughbrickbase.png)
[Source image for BRBRICK, BRBRICK2, TILE, and BROWN2](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/brbrickbase.png)
[**ZDoom forums post containing all of the above textures**](https://forum.zdoom.org/viewtopic.php?f=37&t=31139&p=993589#p985597)

[Old BROWN2 source image 1](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/BrightBrownsrc2.png)
[Old BROWN2 source image 2](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/BrightBrownsrc.png)
[BROWN3 source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/brown2.png)
[Old DARKROCK source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/darkrock2.png)
[DARKROCK source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/darkrock3.png)
[Unused DARKROCK source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/darkrock.png)
[Truecolour old DOGLDIR](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/DOGLDIR.png)
[Truecolour DOKGRIR](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/DOKGRIR.png)
[DORED source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/doredsrc.png)
[FLAT5_3 source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/flatsrc.png)
[Unused MUD](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/mud.png)
[Source image for MC, BROWN1, and BROWN5](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/mudsrc2.png)
[Source image for MOULD](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/mudsrc.png)
[Unused NATROCK source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/natrock5.png)
[NATROCK source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/natrock6.png)
[Another unused NATROCK source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/natrockc2.png)
[BROWNx/MARBLE1 panel source image 1](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/panelsrc.png)
[BROWNx/MARBLE1 panel source image 2](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/panelsrc2.png)
[Unused source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/wallsrc.png)
[WALL78_1 source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/wallsrc3.png)
[MUD source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/wallsrc2.png)
[MARBLE1 source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/kc_wall78_1_11.png)
[Unused flat source image](http://www.ciinet.org/kevin/myimages2/doom/freedoom/textures/kc_flat5_3_11.png)
[**ZDoom forums post containing all of the above textures**](https://forum.zdoom.org/viewtopic.php?f=37&t=31139&p=982583#p982583)

### CODE REVIEW

**Comment by Talon1024** [comment]
Well, I tried.

Generally, when I'm making this stuff, I try to match the colours, and use different patterns that vaguely match the original texture theme. For example, the original BROWN3 had a wood pattern on it, but I chose to use a sandstone pattern instead.

**Comment by AXDOOMER** [comment]
Be sure to be as close as the original. If you use textures with different colors or material, you will break the theme of levels and pwads. If you don't use the same patterns, you will break the texture aligning.

**Comment by AXDOOMER** [comment]
That new `dirbri2` looks great!

**Comment by AXDOOMER** [comment]
`brbrick.gif` and `brbrick2.gif` are very nice too! Good work! These textures definitively needed to be done.

**Comment by Voros2** [comment]
brbrick and brbrick2 don't look like bricks to me :/ more like a wall made of mud. Might be a good idea to break parts of the wall into rectangular segments and try to make it look as natural as possible.

**Comment by AXDOOMER** [comment]
Yeah, they look like dirt bricks. I still think they are very nice.

**Comment by Talon1024** [comment]
Despite the fact that my new BRBRICK stuff looks nice, I think it might be too similar to the original BRBRICK texture.

**Comment by AXDOOMER** [comment]
It think it's just fine. It's not plagiarism or anything, you're not even near. The point of Freedoom is to have textures that are very close to the original so it works with PWADs. 

brbrickbrbrick
brbrick2brbrick2

Perfect :feelsgood: :ok_hand:

**Comment by Talon1024** [comment]
I have another pattern for the TILE patch, which I'll commit in case the current one is problematic.
tile2

**Comment by Proluiz** [comment]
These edits looks awsome.

**Comment by Talon1024** [comment]
Links to preview WADs added.

**Comment by Voros2** [comment]
👍🏾 So far, so good.

**Comment by Talon1024** [comment]
I updated the first preview WAD, and the OP.

**Comment by AXDOOMER** [comment]
Nice! More ugly placeholders disappearing! Good work.

**Comment by chungy** [comment]
I apologize for letting this sit unattended for so long. Thanks!

**Pull request merged**
