### PR TITLE
sounds: updated DSBOSSIT sound

### PR DESCRIPTION
**Pull request by Failsafe538**
I made a new DSBOSSIT for this

### CODE REVIEW

**Comment by Ferk** [comment]
What's wrong with the current one?
Imho, the current one sounds more demonic/evil, this one sounds how the sims talk.

**Comment by AXDOOMER** [comment]
The current one is better.

**Comment by MatthewTheGlutton** [comment]
The current one is spookier, shorter and more to the point.

Also what Ferk said.

**Comment by igdegoo** [comment]
Sounds like a demon on the phone underwater

**Comment by fragglet** [comment]
Closing based on feedback

**Pull request closed without merging**
