### PR TITLE
levels: create c3m5

### PR DESCRIPTION
**Pull request by BeachThunder**
c3m5 now exists

### CODE REVIEW

**Comment by NickZ** [comment]
Hey, thanks for the PR! This is a really nice level!

A couple of things before I merge this in:

* We should not be giving away the SKAG (BFG) in episode 3 (i.e. without the player discovering a secret), simply because it makes the end boss way too easy. I would change the SKAG to a plasma rifle, and the current plasma rifle pickup to a chaingun.
* The dark cavern is currently way too dark on the default gamma settings. I would bump up the lightness a bit so that it's navigable on gamma level 1.

After those changes, I'll merge this in.

**Comment by Calinou** [comment]
Nice level :slightly_smiling_face:

I think I spotted a texturing error in the lava cavern (the one behind the yellow key door). The first step uses a lava texture instead of a gravel texture:

screenshot_doom_20190217_140451

**Comment by BeachThunder** [comment]
@NickZ done and done. I also made a few other minor adjustments while I was at it. 

@Calinou, it wasn't an error, I wanted to make it look like lava was covering the bottom step. But, yeah, in retrospect, it's probably better if it's a gravel texture. Thanks.

**Comment by NickZ** [comment]
Thanks! Merged!

**Pull request merged**
