### PR TITLE
credits: additional music credits.

### LINKED ISSUE #1134: Additional music credits.
Korp's current E1M6 track is a remix of "Dave3D35" by jute.
Korp's current E1M9 track is a remix of "Dave3D42" by jute.

I've no idea how to use GitHub - so I don't know how to PR this myself.

### PR DESCRIPTION
**Pull request by mc776**
Closes #1134.

### CODE REVIEW

**Review by selliott512 — APPROVED** [review]
I have no idea who produced which music, so outside of that here's what I checked and noticed. None of the following is relevant to this change, but they are things I thought I'd mention:

1. Like with Freedoom1 and Freedoom2 FreedDM is divided into sections, but without headers / explanation.
2. No obvious spelling mistakes, good.
3. All CnMn references were replaced with EnMn, good.
4. The following MID files are referenced, but don't exist:

- crudreams2.mid
- crudreams3.mid
- crudreams.mid
- ctf2.mid
- dave3d05.mid
- dave3d07.mid
- dave3d09.mid
- dave3d35.mid
- dave3d42.mid
- Doom1.mid
- Doom2Alt.mid
- d_stlks3.mid
- e1m1.mid
- freedoom2.mid
- freedoom3.mid
- freedoom.mid
- map01.mid

**Comment by mc776** [comment]
> The following MID files are referenced, but don't exist:

The file names are just stand-ins for tracks that otherwise didn't have titles. I'm assuming that they were the file names the tracks were originally submitted under.

**Comment by unithecutie** [comment]
> I have no idea who produced which music, so outside of that here's what I checked and noticed. None of the following is relevant to this change, but they are things I thought I'd mention:
> 
> 1. Like with Freedoom1 and Freedoom2 FreedDM is divided into sections, but without headers / explanation.
> 4. The following MID files are referenced, but don't exist:

answering 1. The reason for FreeDM sections is a short visual break that @mc776 had placed in there after I had submitted this.

and answering 4. These were the file names when submitted: all of these are from when this repo had symbolic links to contributions. (look for history marking "de-symlinkify")

**Comment by unithecutie** [comment]
"freedoom2.mid" and "freedoom3.mid" were obtained from the Doomworld submission [here](https://www.doomworld.com/forum/post/1723287).


"dave3d##" are from [here](https://github.com/freedoom/freedoom/tree/29b50746e268ae2fbecde2723ec1018c2dc3e43c/musics/jute).

"crudreams2.mid", "crudreams3.mid", "ctf2.mid", "e1m1.mid" and "map01.mid" are from [here](https://github.com/freedoom/freedoom/tree/29b50746e268ae2fbecde2723ec1018c2dc3e43c/musics/ralphis).

"d_stlks3.mid" is from [here](https://github.com/freedoom/freedoom/tree/29b50746e268ae2fbecde2723ec1018c2dc3e43c/musics/vicious).

"freedoom.mid" is from Varis Alpha's MIDI files - [here](https://www.doomworld.com/forum/topic/130499).
image

**Pull request merged**
