### PR TITLE
Improved Switchs

### PR DESCRIPTION
**Pull request by Xindage**
DPstudio improved the switchs adding depth and glowing to them.

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Great work :slightly_smiling_face:

**Comment by fragglet** [comment]
Looks good in general, my only criticism is that I'm not sure the "light glowing" effect works very well - in-game it looks like the switch is "leaking" or broken in some way. Can we scale it back a bit and remove the glow?

**Comment by Xindage** [comment]
Well i'm just posting here, i can't ready edit graphics right now, dpstudio is actually ok with fine polishing, if someone want fell free to.

**Comment by Xindage** [comment]
closed, continue in #711, sorry.

**Pull request closed without merging**
