### PR TITLE
Aquatex fix

### PR DESCRIPTION
**Pull request by Voros2**
Meant to be a solution for https://github.com/freedoom/freedoom/issues/323 (tutti frutti errors).
Redefined several texture definitions in textures.cfg so that all textures have a height of 128.

### CODE REVIEW

**Comment by fragglet** [comment]
Is this confirmed to fix tutti-frutti?

My memory of vanilla tutti-frutti issues is that textures cannot tile properly if they are not a power of 2 (16, 32, 64, 128). So if you have a texture that is 12 pixels tall or 24 that can be a problem, but if it's 64 it shouldn't make any difference.

**Comment by Voros2** [comment]
I did what jewellds showed on the issue 323. Most of the textures are now 128 in height.

**Comment by fragglet** [comment]
[Looks like I was wrong!](https://doomwiki.org/wiki/Tutti-frutti_effect)

> If a wall is taller than its texture, then the texture is tiled vertically. But the Doom rendering engine starts new tiles only at heights of 128, 256, 384, etc. If the texture is less than 128 units tall, horizontal bands will be left undefined.

**Comment by fragglet** [comment]
Merged - thanks.

**Comment by Voros2** [comment]
Shouldn't https://github.com/freedoom/freedoom/issues/323 be closed now, or are you keeping it open for any further problems?

**Pull request merged**
