### PR TITLE
patches: fix some aliasing issues on rw16_4.

### PR DESCRIPTION
**Pull request by mc776**
TIL it's supposed to be an old painting of a nude (winged?) female figure descending upon a welcoming crowd of other figures. From that one hard vertical line down the middle I thought it was from an old city sky texture or something!

### CODE REVIEW

**Review by SafinW — APPROVED** [review]

**Comment by SenhorFlibble** [comment]
Is the source image for the painting known?

**Comment by mc776** [comment]
It looked so 18th-century I never even thought to question its public domain status...

**Comment by mc776** [comment]
Throwing this one out there just to see if it sticks: consider replacing with details from a much more recognizable famous public domain painting:
garden

**Comment by mc776** [comment]
I am advised that the current is Bouguereau's Birth of Venus:
https://en.wikipedia.org/wiki/The_Birth_of_Venus_(Bouguereau)
venus

**Comment by mc776** [comment]
And now I understand where that weird vertical line comes from.

Feel free to close this if the edit makes the hips a little too *controversial*.

**Pull request merged**
