### PR TITLE
patches: remove bright spots on edge of gargoyle.

### PR DESCRIPTION
**Pull request by mc776**

### CODE REVIEW

**Review by Big-the-Fat — APPROVED** [review]
Yes.  A good tweak.  Small things make a big difference.

**Review by selliott512 — APPROVED** [review]
Looks good.

If you feel like making more changes IMHO the grey pixels around the perimeter are suboptimal on a non-grey surface.

**Comment by mc776** [comment]
> If you feel like making more changes IMHO the grey pixels around the perimeter are suboptimal on a non-grey surface.

Do any textures actually do that right now? For me the difference very easily gets lost in the wood grain but then again so did these green dots.

**Comment by Xindage** [comment]
> > If you feel like making more changes IMHO the grey pixels around the perimeter are suboptimal on a non-grey surface.
> 
> Do any textures actually do that right now? For me the difference very easily gets lost in the wood grain but then again so did these green dots.

maybe this one? still this texture is yet not used in any freedoom map 
image

**Comment by mc776** [comment]
tbh i have no idea why that texture exists. Anyway there's no way to get that to blend right without making the existing "dark mode" textures look at least as bad if not worse.

If it looks okay on the wood I think it's ready to merge.

**Pull request merged**
