### PR TITLE
Add back Picklehammer's map05 as map29's midi

### PR DESCRIPTION
**Pull request by Mr795**
I decided to add Picklehammer's Map05 Back as Map29's music because to me it fits well with the atmosphere and style of the map and its good for a level that's right before the final level of the game due to the midi's intensity.

### CODE REVIEW

**Comment by unithecutie** [comment]
Would be nice if the original organ version was restored, but that's just me being biased towards the original "grand cathedral"-aesthetic. :)

And please, remember to update `CREDITS-MUSIC`!
This would be formatted as `MAP29: "Mists Over the Mire" by Tyler "Picklehammer" Pantella, modified by Obsidian Plague and m`

**Comment by Mr795** [comment]
oh. yeah i actually kind of like the organ better. ill get straight to adding the OG Picklehammer version. and updating the credits music, thanks for letting me know to do that by the way

**Comment by Mr795** [comment]
it was map05 in 0.5 and i have that version so ill extract its midi with slade.

**Comment by unithecutie** [comment]
Don't extract it with SLADE, use the original pre-MUS conversion.

[d_map29.mid](https://www.dropbox.com/scl/fi/9lijx19w804vjyb15esio/d_map29.mid?rlkey=daga1n84l8wff9jh5n3amyxuz&dl=0)

**Comment by Mr795** [comment]
alright ill commit the midi

**Comment by Mr795** [comment]
the second commit from now is an update to CREDITS-MUSIC.

**Review by unithecutie — CHANGES_REQUESTED** [review]
A nitpick, but to main consistent formatting, could you please decapitalize "the"?

**Comment by mc776** [comment]
Line 173 also needs a note `(moved to Map29, not removed)` and that section needs to have `MAP29: freedoom.mid by Varis Alpha` added.

**Comment by mc776** [comment]
> A nitpick, but to main consistent formatting, could you please decapitalize "the"?

The "the"s and similar are not capitalized in the other titles.

**Comment by Mr795** [comment]
> Line 173 also needs a note `(moved to Map29, not removed)` and that section needs to have `MAP29: freedoom.mid by Varis Alpha` added.

i guess you mean the 0.12.1 section?

**Comment by mc776** [comment]
yes

**Comment by Mr795** [comment]
alright done updating the music credits.

**Comment by mc776** [comment]
One nitpick before I finally step away from the computer for once: can you get rid of the period after "removed" to keep it consistent with the others?

**Comment by Mr795** [comment]
ok

**Review by mc776 — APPROVED** [review]

**Comment by mc776** [comment]
I considered leaving this up for further discussion but the old track did Not sound good in OPL.

**Pull request merged**
