### PR TITLE
lumps: Updated custom ENDOOM screens

### PR DESCRIPTION
**Pull request by Anonysussy**
These were a revised version of the previous custom ENDOOM screens i made a few weeks/months back probably, i don't have much involvement in the previous PR since it got closed off immediately, these new revision fixes a bunch of problems from the previous one.
Screenshot 2024-03-21 205746
Screenshot 2024-03-28 202739

### CODE REVIEW

**Review by Snoucher — CHANGES_REQUESTED** [review]
These are some great changes to the endoom screens, but I think the website portion of the screen has a lot of dead space. Perhaps you could change it to the original text for the website portion to avoid it?

**Comment by Anonysussy** [comment]
> These are some great changes to the endoom screens, but I think the website portion of the screen has a lot of dead space. Perhaps you could change it to the original text for the website portion to avoid it?

**Comment by Anonysussy** [comment]
> These are some great changes to the endoom screens, but I think the website portion of the screen has a lot of dead space. Perhaps you could change it to the original text for the website portion to avoid it?

I've come up with the workaround, but when I asked about it fraggle requested me to just remove the row leading to said empty space, (also the closing PR was a misclick my bad)

**Comment by Anonysussy** [comment]
> These are some great changes to the endoom screens, but I think the website portion of the screen has a lot of dead space. Perhaps you could change it to the original text for the website portion to avoid it?

Would probably going to work on it though

**Comment by Anonysussy** [comment]
Screenshot 2024-04-03 194853
i think these should probably work out the empty space, also experimenting with the color

**Review by Xindage — APPROVED** [review]

**Pull request merged**
