### PR TITLE
buildcfg: FREEDOOM lump for Phase 1 and 2 only

### PR DESCRIPTION
**Pull request by Voros2**
FreeDM contains both FREEDM and FREEDOOM lumps. These two lumps are identical to one another, so make FREEDM be the only lump present in FreeDM.

### CODE REVIEW

**Comment by chungy** [comment]
The contents aren't really the important part. The existence of the FREEDOOM lump is good for detecting that it is a Freedoom IWAD.

**Comment by Voros2** [comment]
Then is the FREEDM lump needed?

**Comment by chungy** [comment]
Neither are strictly needed for the IWADs to work, but they are useful for source ports' game detection code.

**Comment by Voros2** [comment]
Isn't that the purpose of the FREEDM lump in FreeDM?

**Comment by chungy** [comment]
Partially, for FreeDM specifically. There's no harm in having both lumps in the IWAD.

**Comment by Voros2** [comment]
There's no harm in having __EUREKA lumps either. The FREEDM lump is supposed to be used for recognising FreeDM in source ports, and apparently the FREEDOOM lump too. Why have both, when both serve the same purpose?

**Comment by chungy** [comment]
__EUREKA lumps have no utility function, these ones do.

Removing them isn't happening.

**Pull request closed without merging**
