### PR TITLE
Four new demos for phase 2.

### PR DESCRIPTION
**Pull request by Xindage**
Made by Xindage and Korp.
POV: D1 Korp / D2 Xin / D3 Xin / D4 Xin

All of them are 2 players multiplayer, the POV used dies at the end of the demo.
Maps: 04 - 10 - 22 - 23

### CODE REVIEW

**Comment by Xindage** [comment]
btw demo 22 is going to desync if you use the artifacts build, because this demo was recorded with # #1169 applied.
Just a note.

**Comment by selliott512** [comment]
Please also update `lumps/README.DEMO`. Don't worry about overwriting my name - I'm totally fine with that.

Review and likely approval coming soon.

**Comment by Xindage** [comment]
i dont think the order or who is player 1 and 2 matter so i'll just add me and korp, is that fine?

DEMO1: MAP04 by Xindage and Korp - v0.13.0
DEMO2: MAP10 by Xindage and Kor - v0.13.0
DEMO3: MAP22 by Xindage and Kor - v0.13.0
DEMO4: MAP23 by Xindage and Kor - v0.13.0

and what version i should use? 13?

**Review by selliott512 — APPROVED** [review]
Looks good. I watched all four demos in Chocolate Doom. The only error is the first one is actually MAP03, not MAP04.

They are a bit longer than the demos I record, but that's ok. There's a variety of opinion about how long demos should be. FWIW tere's how long it took for me to get the prompt back after running `time chocolate-doom -playdemo ...`

| Level | Time |
| ------------- | ------------- |
| MAP03 | 1:28 |
| MAP10 | 2:38 |
| MAP22 | 2:42 |
| MAP23 | 2:16 |

**Comment by selliott512** [comment]
> and what version i should use? 13?

Yes, still the same version.

**Comment by Xindage** [comment]
they're a little longer because its harder to coordinate 2 players, but its still short.

**Pull request merged**
