### PR TITLE
manual: Spanish translation for goals statements.

### LINKED ISSUE #1095: manual: Spanish translation needed for statement of objectives.
#1094 was a important, (in hindsight) overdue and welcome addition.

I know in English people often use "libre" when they want to make this clarification but [I am advised that the same problem may exist in Spanish for this word](https://www.spanishdict.com/translate/libre). (definition 4) But even if it didn't, given the comprehensive nature of the manual (how many FPS manuals *explain what an FPS is*?) an explicit statement of FD's goals is a good addition to have in both versions.

### PR DESCRIPTION
**Pull request by MrAlaux**
Fixes #1095.

While we're on it, I'd say the rest of the spanish manual needs a review. I might do that later on.

### CODE REVIEW

**Comment by mc776** [comment]
> que el proyecto solamente apunta a ser una alternativa a Doom que puede obtenerse gratuitamente. Pero no es así.
I like how the word "solamente" is so much longer in Spanish than in Englilsh, which helps with that concern I had about that last sentence in this paragraph...

**Review by mc776 — APPROVED** [review]

**Comment by mc776** [comment]
I'm tempted to merge this immediately but I'll leave it up for a bit in case there's anything to add or anyone spots a typo or something.

**Comment by mc776** [comment]
Re: rest of manual, I should point out we've got an outstanding non-trivial edit in #1091 which adds and removes quite a few things. If my *very crude attempts* at making corresponding changes to the Spanish version are more misleading than helpful I have no issue reverting the changes on that PR (or at least reverting everything but the changed still-untranslated item names) so that that PR is English-only and the result can be translated properly from scratch.

**Comment by MrAlaux** [comment]
I wasn't going to simply revise the spanish manual by itself; the idea is to read through the entire english manual and then review the spanish translation, rewriting parts of it as I go along -- if prudent, of course.

**Pull request merged**
