### PR TITLE
New d_dm13.mid music

### PR DESCRIPTION
**Pull request by rostuhan**
Current d_dm13.mid is using the e1m1 music, so I've composed this to add a unique MIDI to the wad.

### CODE REVIEW

**Comment by mc776** [comment]
Could we use this for DM07 instead? (see #965)

I think the upbeat tune actually fits that map better than DM13.

**Comment by rostuhan** [comment]
Sure, replacing the glitched soundtrack is more important than replacing a reused audio. Do I have to edit anything or do you edit it?

**Comment by rostuhan** [comment]
I'll close this to make a new pull request that will replace the DM07 music instead.

**Comment by rostuhan** [comment]
(This pull request was moved to #1008)

**Pull request closed without merging**
