### PR TITLE
New MIDIs

### PR DESCRIPTION
**Pull request by Voros2**
Uses blueworrior's new MIDI submission.

I assigned the tracks to slots that use double duty on music tracks, and made sure it was appropiate enough for the slots.

### CODE REVIEW

**Comment by Voros2** [comment]
Added some more MIDI from blueworrior that wasn't submitted before.

**Comment by Voros2** [comment]
Blueworrior gave me higher pitched versions of the MIDI.

**Comment by fragglet** [comment]
Cool. Blueworrior isn't listed in CREDITS - can you update it? We want to make sure everyone who has contributed is credited.

**Comment by fragglet** [comment]
Thanks!

**Pull request merged**
