### PR TITLE
Based on Inuk's reports, Stratos posted these fixes on discord:

### PR DESCRIPTION
**Pull request by Xindage**
map03: (linedef 1129) Misaligned texture.
map08: (linedef 1782) W1 blocks door until spent, you have to faceplant onto the door to reach it. [X]
map15: (sector 492) Can grab items by slamming into the cover.
map17: Very early finish by just running from the walkway to the exit (SR40) [X]
map22: (sector 189) Thin secret sector, can run over without tagging. (sector 134) Secret can be robbed by slamming into the cover [X]

Note: Fixes marked by X means that the map structure was a slight modified in someway, it may break demos.
TODO: Provide Statros credits if needed.

### CODE REVIEW

**Comment by mc776** [comment]
Looking at this in SLADE everything looks good to me except Lines 446, 1035, 29 and 30 need to be flipped to address #996.

**Comment by Xindage** [comment]
> Looking at this in SLADE everything looks good to me except Map17 Lines 446, 1035, 29 and 30 need to be flipped to address #996.

can you provide the changes as attachment or directly pull in my branch? i cant map right now.

**Comment by mc776** [comment]
Here it is as a zip but I can't build the nodes with the "proper" version of ZenNode until I get home
[map17.zip](https://github.com/freedoom/freedoom/files/13232827/map17.zip)

**Comment by mc776** [comment]
Re: Map08, I want to suggest an alternate solution: make the trigger a new line *inside* the door.
[map08alt.zip](https://github.com/freedoom/freedoom/files/13233349/map08alt.zip)

This ensures that the trigger only happens after the blue door has been opened and not when the player approaches the door before getting the blue key for whatever reason.

**Comment by mc776** [comment]
Here's all 5 maps, with the Map17 linedef fix but *not* my proposed Map08 alternate fix, with all nodes rebuilt:
[xfix.zip](https://github.com/freedoom/freedoom/files/13233822/xfix.zip)

I have no idea how to "pull directly in your branch".

**Comment by mc776** [comment]
Maybe this is something to be addressed later, but I can't help but notice that projectiles shift upwards when they explode after hitting that central platform (and this is a pre-existing issue, I just noticed it now):
DOOM00

**Comment by Xindage** [comment]
only map17 was affected by your changes
add your proposed fix for map08?

**Comment by mc776** [comment]
I'll post the fix for this in about 2 hours
DOOM01

**Comment by mc776** [comment]
[map17.wad.zip](https://github.com/freedoom/freedoom/files/13234441/map17.wad.zip)
This addresses both issues with Map17:
- The control sectors have been merged back into their rising steps onto the fountain.
- At 64 instead of 48, the only place in vanilla where you can shoot the fountain and get that explosion-on-higher-floor effect is from the first step on the stairs leading into the house, rather than from nearly anywhere as the original 48 height allowed.

I have tested this with the tripod and it is still able to move through that area:
DOOM00

**Comment by mc776** [comment]
Could you add this E2M1 to this PR as well? It fixes the exit portal so it eats projectiles like the others.
[e2m1.wad.zip](https://github.com/freedoom/freedoom/files/13234580/e2m1.wad.zip)

**Comment by Xindage** [comment]
i'll be doing this in a minute

**Comment by Xindage** [comment]
with that i'll be focusing on some couple of multiplayer demos, no more map changes please.

**Review by mc776 — APPROVED** [review]

**Pull request merged**
