### PR TITLE
Restore the original "Riders of Hell" by Picklehammer.

### PR DESCRIPTION
**Pull request by unithecutie**
I **absolutely despise** the instrument choice that was used in the new version.
This one is also the pre-.MUS conversion file.

No offense, Matt; but this is pretty much exactly what you did to "Mists Over the Mire" as well but on a bigger scale.

### CODE REVIEW

**Comment by mc776** [comment]
Just a matter of personal choice then.

If anyone's working on a new track they're welcome to submit it.

**Comment by mc776** [comment]
Just to be clear, I'm closing this summarily like this because I think there's a real good chance someone out there *does* have something that they might want to replace this entire track with.

**Comment by unithecutie** [comment]
> something that they might want to replace this entire track with.

These are potential candidates.

["Fun is Infinite at AGM" by continuum.mid](https://www.dropbox.com/scl/fi/jn7j6vbgmtis03biiiug7/fun_is_infinite_at_agm.mid?rlkey=icf4vlch9dm5tlcxm0rj612c4&dl=0)
image

["The Human Race" by Mark "TheMisterCat" McGill-Smith](https://www.dropbox.com/scl/fi/o6xqaf14mejrxb6pbqz48/TheMisterCat_-_The_Human_Race.mid?rlkey=553z0i8k9yx2yydp0xenxtrgg&dl=0)
image

["Vitals Rising" by Mark "TheMisterCat" McGill-Smith](https://www.dropbox.com/scl/fi/mfviss4n626lf8bx0u9hc/d_themis.mid?rlkey=e6eoocs3rqx09z04en3f6qyxq&dl=0)
image

**Comment by mc776** [comment]
I'm looking at the replaced stuff and MAP21 "Violence Culture" is also workable...

**Comment by unithecutie** [comment]
> I'm looking at the replaced stuff and MAP21 "Violence Culture" is also workable...

"Music for Freedoom 9": 0.10's MAP18 is also a great candidate.

**Comment by unithecutie** [comment]
"Music for Freedoom 9" has a **much** of a faster rhythm than "Violence Culture": I find it catchier but that's just a matter of personal opinion again.

**Comment by mc776** [comment]
After running a botmatch with all of them playing, here's my preference so far in descending order:

MFF9
Human Race
Fun
Themis

I retract my suggestion for "Violence Culture" as it's not every good for DM.

**Pull request closed without merging**
