### PR TITLE
Sprites: mazmon sboxa0

### PR DESCRIPTION
**Pull request by raymoohawk**
mazmon has edited my shellbox based on forum feedback

### CODE REVIEW

**Comment by chungy** [comment]
Use --author please

**Comment by raymoohawk** [comment]
ah sorry about that :( i forgot to check how to do it

**Comment by NickZ** [comment]
so what you do is, in mobaxterm, go to the freedoom directory, and then do:

git commit --append --author "mazmon <THEIR@EMAIL.COM>"

then press "ctrl-o" and then enter to save it.

**Comment by chungy** [comment]
> git commit --append

I think you mean --amend, but that wouldn't be necessary (or recommended) when doing the commit first :P

**Comment by NickZ** [comment]
yeah, only do that if you have already made the commit

**Pull request closed without merging**
