### PR TITLE
Added old C2M3 music back into Freedoom as C1M3!

### PR DESCRIPTION
**Pull request by jadenquinn**
I loved this track so much, I felt that it couldn't go to waste, so I added it back into Freedoom: Phase 1 as C1M3 instead of C2M3, since C1M3's midi was always... not as high regarded as some of the others in my honest opinion.

### CODE REVIEW

**Comment by jadenquinn** [comment]
I'm really hoping this worked. I have literally no idea what I'm doing, I'm trying to replace C1M3's midi. I did this a completely different way last time I contributed.

**Comment by jadenquinn** [comment]
Idk if this will get done, but I did a couple minor edits to Freedoom maps too including the readding of the soulsphere in E4M8 (for some reason it wasn't there before even though the mapset the maps are actually from does have it there), and a little weapons cache behind the lift of C3M4/C3M3 (idk which to refer to, it's the one that in the release is still C3M4) that I don't think actually made it into Freedoom at all, I get that it could have been perceived as very glitchy, that's by design for the most part, as it's supposed to seem like the rocket launcher just appears out of nowhere, at least that's how I designed it.
Name: Jaden LeMieux
eMail: jadenquinn8@hotmail.com

Thanks!
-j

**Comment by selliott512** [comment]
It looks like you have one git commit that modifies `musics/d_e1m3.mid`, so seems like a reasonable pull request to me. I haven't listened to it, but the looks like a reasonable pull request at a casual glance.

**Comment by mc776** [comment]
I just gave both songs a listen.

omg the song in this PR is *so* much better, both for this level and generally!

Please merge this before release.

**Review by fragglet — APPROVED** [review]

**Pull request merged**
