### PR TITLE
sprites: new fist.

### PR DESCRIPTION
**Pull request by mc776**
With modifications, see https://github.com/freedoom/freedoom/issues/1031.

Addresses #760.

### CODE REVIEW

**Comment by Xindage** [comment]
Do these really looks better? for me it seems that the hand is made of plastic.

**Comment by mc776** [comment]
It's better than the current sprite at least, which has all the same problems except the proportions are a bit off and feels like it's coming out of the player's right ear - it's only less noticeable because we're more used to seeing it.

**Review by selliott512 — COMMENTED** [review]
I like it. It has a cleaner (Less hairy? Less gloved?) look.

However, the four modified PNGs are color type 6 (RGBA). Ideally they should be color type 3 (indexed, and ideally with the Doom palette).

**Review by selliott512 — APPROVED** [review]

**Comment by fragglet** [comment]
Just a quick note - I missed the original PR but I wanted to say that this new fist is **awesome**. Probably the most satisfying punch animation I've seen in any Doom mod.

**Pull request merged**
