### PR TITLE
New d_dm07 music

### PR DESCRIPTION
**Pull request by rostuhan**
I've originally made [this (#1006)](https://github.com/freedoom/freedoom/pull/1006) pull request, but I didn't know about [this (#965)](https://github.com/freedoom/freedoom/issues/965) glitch, so I've made this fork and the pull request.

### CODE REVIEW

**Comment by mc776** [comment]
Just tried building it now and listening in chocolate/opl, sounds good to me.

How should you be credited? (See credits file for format https://github.com/freedoom/freedoom/blob/master/CREDITS)

**Comment by rostuhan** [comment]
I'm not really sure what does each letter mean, does "S" stand for username?

**Comment by rostuhan** [comment]
If I'm right, then it's like this:
```
S: rostuhan
E: rostuhan123@gmail.com
```

**Comment by mc776** [comment]
I'm not sure what S stands for exactly but yeah that's where we're putting people's online handles.

Actually could you add that directly to the credits file as part of the PR? That would keep everything in more or less one place. (I think right now we're just adding people to the end of the file, no special order or anything)

**Comment by rostuhan** [comment]
> Actually could you add that directly to the credits file as part of the PR?
Sure.

**Comment by rostuhan** [comment]
Done, I've edited the branch.

**Review by mc776 — APPROVED** [review]

**Pull request merged**
