### PR TITLE
sprites: new tech lamps by Cascade

### PR DESCRIPTION
**Pull request by Talon1024**
These are from a WAD Cascade submitted on the Discord server

### CODE REVIEW

**Comment by mc776** [comment]
Whatever my thoughts about CANDA0, these ones are pretty clearly an improvement over the current. (Someone will need to PR an update to GZDoom's light definition files after this though)

That said, it would be great if the light glow animation could affect the shading on the body of the lamps themselves - the current short lamp has that though the current tall lamp does not.

**Comment by mc776** [comment]
DOOM02
DOOM01
DOOM00

Since the entire light appears fullbright and the brightness of the actual light source portion visibly changes I think it would be nice to have the bottom of each column get a bit darker (and that brown reflection bit on the right could be darker in any event), but if another maintainer thinks it's enough of an improvement over the existing sprites to go as-is I have no objections to merging it now.

**Comment by mc776** [comment]
One possible variant on the tall lamp. I've gotten rid of the side shaft panels because they tended to detract from the "lamp" aspect of it, and it now has four prongs below the light source so it's radially rather than bilaterally symmetrical.
DOOM00
tlmp-spiral

**Comment by mc776** [comment]
And the other one.
DOOM00
tlmp2

**Comment by Cescade** [comment]
Not too fond of what you did to the tall lamp but could you smoothen the transition of the fade of the light on the bronze "screw" pipe on the bottom?

**Comment by mc776** [comment]
The animation or along the length?

**Comment by mc776** [comment]
How's this?
tlmp
DOOM00

**Comment by Cescade** [comment]
Yeah

**Comment by mc776** [comment]
Sweet.

@Talon1024 if you can update this and #1177 I think both will be ready to merge.
tlmpa0
tlmpb0
tlmpc0
tlmpd0
offset should be (9,79)

**Review by mc776 — APPROVED** [review]

**Pull request merged**
