### PR TITLE
Update e2m4:

### PR DESCRIPTION
**Pull request by Xindage**
Removed unused textures.
Fixed missing textures alignment.
Fixed 2 ceiling using wrong flat.
All liquids sectors near techwalls now damage properly. All secrets now appears on automap.
Fixed one of the DM closets near rockets launcher opening in singleplayer/coop.

### CODE REVIEW

**Comment by mc776** [comment]
I'll give this a quick run tonight just in case.

Not a huge deal, but I am wondering: is there any reason to keep those two sectors behind the portal at the start (sectors 296 and 297) instead of just making the fireblu a 1-sided line? I only even noticed it because SLADE gave a missing-texture warning there.

**Comment by Xindage** [comment]
> I'll give this a quick run tonight just in case.
> 
> Not a huge deal, but I am wondering: is there any reason to keep those two sectors behind the portal at the start (sectors 296 and 297) instead of just making the fireblu a 1-sided line? I only even noticed it because SLADE gave a missing-texture warning there.

Shot rockets in the teleport or any other projectiles and you'll know why.

**Review by mc776 — APPROVED** [review]

**Comment by mc776** [comment]
I still want to play it through once just to say someone other than the author did before it was merged, but I'll mark this as approved in case someone else beats me to it.

**Comment by Xindage** [comment]
i already got 2 people to play this map before the changes so i'll wait you.

**Comment by mc776** [comment]
You mean they played before the changes in this PR, or they played with the changes in this PR but before you posted it?

**Comment by Xindage** [comment]
they played before the PR (including myself) that's how we found these bugs and i fixed them i played after the fix and nothing weird was found after it.

**Pull request merged**
