### PR TITLE
sprites: remove white trim from red armor.

### PR DESCRIPTION
**Pull request by mc776**
EDIT: here's how it looks after the later additional tweak:

Also fix a shading issue near the bottom of the lit-up yellow armor frame.

### CODE REVIEW

**Comment by Talon1024** [comment]
What's wrong with the white trim on the red armor? To me, it makes it look inspired by Japanese Samurai armor.

**Comment by mc776** [comment]
The graphic is fine on its own, but ingame it looks way too much like a Santa suit.

If everyone likes the current version though I don't mind closing this PR... let's see what else folks have to say.

**Review by Xindage — APPROVED** [review]
I like this new version, its more simple and easy on eyes

**Comment by mc776** [comment]
I accidentally put the new ARM2* offsets into #947 with the net result that after resolving conflicts this PR does not purport to change the buildcfg in any way.

Anyway it should be ready to merge now.

**Comment by selliott512** [comment]
I'm happy with the new one as well. Merge it?

**Pull request merged**
