### PR TITLE
new pistol

### PR DESCRIPTION
**Pull request by Voros2**
This time, sprites now have the cyan background AND offset values for the pistol.

### CODE REVIEW

**Comment by CraftedPixel** [comment]
Cool, but the hand doesn't match well with the fist.

**Comment by Voros2** [comment]
I'm sorry, but what fist? Are you referring to the fists weapon? If so, then yeah. But that didn't stop the new shotgun from being merged.

**Comment by Blastfrog** [comment]
I'm eventually going to make a new fist graphic. The current one is absolute garbage that needs replacement anyhow.

**Comment by Voros2** [comment]
Are you sure this time? You said the same thing last year.

**Comment by Blastfrog** [comment]
I am a bit of a procrastinator, aren't I? Heh. I swear I'll do it... eventually.

**Comment by fragglet** [comment]
@Blastfrog - please don't feel bad! Your contributions to Freedoom are always appreciated. I have plenty of unfinished projects myself.

**Comment by Voros2** [comment]
Speaking of contributions, how comeSoda's new pistol hasn't been merged yet?

**Comment by fragglet** [comment]
It was my understanding that there is some ongoing discussion about this pistol that's blocking it being merged. Maybe that's wrong?

**Comment by Blastfrog** [comment]
I have no idea about anything like that. Looks like general consensus on the forums is positive. Can we please implement it?

**Comment by Voros2** [comment]
Yeah, it was well received by everyone. At first NickZ didn't like it, but he later said that he changed his mind. The same for me. This should be added.

**Comment by AXDOOMER** [comment]
The SSG sprite also need the gloves to be removed.

**Comment by Voros2** [comment]
I'm just hoping someone brings the old SSG.

**Comment by AXDOOMER** [comment]
PISGD0 and PISGE0 are still in the WAD. They are some remaining of the old pistol sprites.

**Comment by Voros2** [comment]
I know. They're not used in game. Leftovers, you might say.

**Comment by Blastfrog** [comment]
I suggest replacing frames D and E with one transparent pixel.

**Comment by AXDOOMER** [comment]
Even though today's computers have huge capacities, we shouldn't waste space in the IWAD with unused data. I guess the only way that these pistol frames are going to be used is if somebody create a dehacked patch that requires them.

**Comment by Voros2** [comment]
Let's just put the idle frame for those two slots. Think that's a better idea.

**Pull request merged**
