### PR TITLE
New Combat Slug muzzle flash by Craneo

### PR DESCRIPTION
**Pull request by Talon1024**

### CODE REVIEW

**Comment by Xindage** [comment]
This definitive an improvement.

**Comment by mc776** [comment]
Looks a lot better, but while you're at it can you make it so that the flash is the same size for all angles? Right now in the H frame it gets way smaller as you get closer to a side view.

(And if you do this please also remember to update the BUILDCFG file so the sprites are given the correct alignments)

**Comment by Xindage** [comment]
talon can you check if this is really ready to commit?

**Comment by Xindage** [comment]
ok i tested the experimental wad to see the difference between the 2 fatsos and well so far it's an improvement.
Bus still this sprites need some rework.

**Pull request merged**
