### PR TITLE
New TEKGRENs by @KorpKat

### PR DESCRIPTION
**Pull request by unithecutie**
These are edited from #1166; and RW39_3/TEKGRENW is intended for #1309.
I really don't want to touch `textures.cfg` again...

### CODE REVIEW

**Comment by mc776** [comment]
As I've said before, I really don't see the point of turning the TEKGREENs into a METAL2 clone.

**Comment by mc776** [comment]
> and RW39_3/TEKGRENW is intended for https://github.com/freedoom/freedoom/pull/1309.

@Xindage did you ask for this? Notwithstanding my previous comments about those things I found the brown worked pretty well to complement the green.

**Comment by mc776** [comment]
Looking at the patches from that old PR and nothing appears to have changed.

Closing.

**Comment by KorpKat** [comment]
Can you please stop closing my pull requests and give me actual criticism.

**Comment by Xindage** [comment]
> > and RW39_3/TEKGRENW is intended for #1309.
> 
> @Xindage did you ask for this? Notwithstanding my previous comments about those things I found the brown worked pretty well to complement the green.

i dont asked nothing... with all respect, if i wanna pr something i can do it myself...

**Comment by mc776** [comment]
Xindage: I figured as much after I'd tagged you and looked closer at the PR.

Korp: I stand by everything I said in the other PR. Nothing about this is an improvement over the existing patches. Your PR for the plat is still open, in fact even approved despite significant personal misgivings about the art direction on my part.

**Review by X64X2 — COMMENTED** [review]
What sort of PR is this ??

**Pull request closed without merging**
