### PR TITLE
patches: improve Plutonia brick textures

### PR DESCRIPTION
**Pull request by Talon1024**
These should look much better, now that they are less rectangular, and have more depth

### CODE REVIEW

**Comment by MatthewTheGlutton** [comment]
Does this affect the tiling and alignment of existing maps? Some of the brick lines are quite different.

**Comment by Talon1024** [comment]
It shouldn't be too different. The biggest difference I see is with the 8-row patches, which are not in the Plutonia IWAD, and are only used in FreeDM, and possibly other Freedoom maps.

**Comment by Xindage** [comment]
they indeed look differently as it has depth now. Some screenshots of freedm map18 that use some of them:
image
image

Looks good to be merged.

**Comment by Xindage** [comment]
So far this one have been in experimental for a time, and i played this map over some times and the textures looks good, going to merge this.

**Pull request merged**
