### PR TITLE
New player death sounds

### PR DESCRIPTION
**Pull request by Talon1024**
Unlike #270, I've converted SeventhSentinel's player death sounds to 8-bit 11025 Hz format so that they will not have white noise when used in Boom or (G)ZDoom.

I've also made SeventhSentinel the author of the commit that changes the sound files, and I've added him to the credits. I got his name from his YouTube channel.

### CODE REVIEW

**Comment by Voros2** [comment]
White noise? I didn't hear any white noise ingame.
And did you get SeventhSentinel's permission to include his name?

**Comment by Talon1024** [comment]
I heard white noise when I used the sounds from the other pull request.
However, I didn't get permission to use SeventhSentinel's name.

**Comment by Voros2** [comment]
That's strange. Well, have you tested your converted sounds ingame also?

**Comment by Voros2** [comment]
And check your speakers/soundcard, will you?

**Comment by Talon1024** [comment]
I did test my converted sounds ingame, and I do believe my (built-in) sound card is just fine.
This white noise issue is [nothing new](https://github.com/freedoom/freedoom/commit/fd9a63129eb248bfc33a609580c76857e4621955).
The only major difference here that I can think of is that I'm using Linux and you're (probably) using Windows.

**Comment by Voros2** [comment]
I'm aware of that, but that did have white noise. Everyone noticed.

No mentioned any kind of white noise for these sounds. Even I still don't hear it. 

You sure its not a problem on your end?

**Comment by Voros2** [comment]
Just to be clear, I tested the SFX in Prboom+ and GZdoom.

**Comment by Talon1024** [comment]
When I tried adding your sounds to a wad in SLADE and convert them to Doom format, I was unable to because the wavs were in the wrong format.
Deutex automatically converts wavs to Doom format when it builds the Freedoom IWADs. I replaced the existing player death sounds in my freedoom repo directory with yours, and when I built the Freedoom IWADs, I noticed the white noise on the death sounds ingame.

**Comment by Voros2** [comment]
Well if you say there is white noise, then so be it. I'll close my PR. Hopefully, the maintainers will merge these player death sounds soon.

**Comment by Voros2** [comment]
For consistency's sake, I think the rest of the sounds should be added eg pain, oofs, etc.

**Comment by Voros2** [comment]
I wonder what's hold up here? Surely, these sounds are better than a zombie groan and the increasingly used Wilhem Scream.

**Pull request closed without merging**
