### PR TITLE
textures: add backwards DOOR3.

### PR DESCRIPTION
**Pull request by mc776**
For maps that do things that might actually give an impression of an ostensibly horzontal-moving door that can be viewed from either side, or a pair of double-doors at the entrance to a level.

### CODE REVIEW

**Comment by Xindage** [comment]
Can we see how it looks?

**Comment by mc776** [comment]
DOOM01
DOOM00

**Comment by MerrittK** [comment]
Looks like a good idea.

**Comment by unithecutie** [comment]
That looks quite nice. :)

**Comment by Xindage** [comment]
that could be useful even for normal doors if the mapper want to make "lock" be on the same sides of the door by using some offsets.

**Review by selliott512 — APPROVED** [review]
I like it. 

I verified that `DOOR3L` is a mirror of `DOOR3`, and that the dimensions match.

**Pull request merged**
