### PR TITLE
New FreeDM titlepic

### PR DESCRIPTION
**Pull request by Mr795**

### CODE REVIEW

**Comment by Mr795** [comment]
this is what the titlepic looks li
freedm_titlepic

**Comment by Mr795** [comment]
by the way i used the other logo png because it was different, thats really it. i tested the wad that came from the completed check and it looked pretty good.

**Comment by Mr795** [comment]
the reason i made this titlepic was that the past one is a tiny bit outdated because the older player sprite. the background for this one is a cropped GZDoom screenshot of the current map20.

**Comment by mc776** [comment]
Not really a huge fan of this - the perspective makes the victim look huge and there's a lot of empty space where the FreeDM logo could have been.

It's tricky to take good FreeDM screenshots because all the map geometry is necessarily much simpler and less ornate than the singleplayer campaign.

I've tried taking a few others:
Screenshot_Doom_20231209_093658 png
Screenshot_Doom_20231209_093649 png
Screenshot_Doom_20231209_093630 png
Screenshot_Doom_20231209_093609 png
Screenshot_Doom_20231209_093551 png

**Comment by mc776** [comment]
Comparison of OP and a touched-up version of the first one I posted:
DOOM00
DOOM01

**Comment by Mr795** [comment]
> Not really a huge fan of this - the perspective makes the victim look huge and there's a lot of empty space where the FreeDM logo could have been.
> 
> It's tricky to take good FreeDM screenshots because all the map geometry is necessarily much simpler and less ornate than the singleplayer campaign.
> 
> I've tried taking a few others: Screenshot_Doom_20231209_093658 png Screenshot_Doom_20231209_093649 png Screenshot_Doom_20231209_093630 png Screenshot_Doom_20231209_093609 png Screenshot_Doom_20231209_093551 png

the huge player sprite must be because i made it manually in a photo editor using the freedoom sprites.

**Comment by Mr795** [comment]
> Comparison of OP and a touched-up version of the first one I posted: DOOM00 DOOM01

that touchup looks way better than mine.

**Comment by Calinou** [comment]
The 4th one in https://github.com/freedoom/freedoom/pull/1224#issuecomment-1848604346 is probably my favorite.

**Comment by Mr795** [comment]
> Not really a huge fan of this - the perspective makes the victim look huge and there's a lot of empty space where the FreeDM logo could have been.
> 
> It's tricky to take good FreeDM screenshots because all the map geometry is necessarily much simpler and less ornate than the singleplayer campaign.
> 
> I've tried taking a few others: Screenshot_Doom_20231209_093658 png Screenshot_Doom_20231209_093649 png Screenshot_Doom_20231209_093630 png Screenshot_Doom_20231209_093609 png Screenshot_Doom_20231209_093551 png

i decided to add the FreeDM logo to the 4th screenshot in this post and commit it

**Comment by Mr795** [comment]
> > Not really a huge fan of this - the perspective makes the victim look huge and there's a lot of empty space where the FreeDM logo could have been.
> > It's tricky to take good FreeDM screenshots because all the map geometry is necessarily much simpler and less ornate than the singleplayer campaign.
> > I've tried taking a few others: Screenshot_Doom_20231209_093658 png Screenshot_Doom_20231209_093649 png Screenshot_Doom_20231209_093630 png Screenshot_Doom_20231209_093609 png Screenshot_Doom_20231209_093551 png
> 
> i decided to add the FreeDM logo to the 4th screenshot in this post and commit it

this is what the edited version looks like:
freedm_title2

**Comment by Mr795** [comment]
> > Not really a huge fan of this - the perspective makes the victim look huge and there's a lot of empty space where the FreeDM logo could have been.
> > It's tricky to take good FreeDM screenshots because all the map geometry is necessarily much simpler and less ornate than the singleplayer campaign.
> > I've tried taking a few others: Screenshot_Doom_20231209_093658 png Screenshot_Doom_20231209_093649 png Screenshot_Doom_20231209_093630 png Screenshot_Doom_20231209_093609 png Screenshot_Doom_20231209_093551 png
> 
> i decided to add the FreeDM logo to the 4th screenshot in this post and commit it

this is what the edited version looks like:
freedm_titlepic

**Comment by mc776** [comment]
My attempt at the regular, and a bit more touchups to make the lighting more dramatic:
DOOM01
DOOM00

(The plasma ball looks janky af either way and will need to be tweaked.)

**Comment by Mr795** [comment]
> My attempt at the regular, and a bit more touchups to make the lighting more dramatic: DOOM01 DOOM00
> 
> (The plasma ball looks janky af either way and will need to be tweaked.)

if the plasma ball gets tweaked would you be able to post the image that doesn't have the bottom text so that if its committed the text doesn't get overlapped?

**Comment by mc776** [comment]
Those are screenshots after I'd built an IWAD using the actual resource.

**Comment by Mr795** [comment]
i think i would prefer less edited because you wouldn't need to find a way to not have an overlapped text in your title screen, which would like a jumbled up mess if it was made into a wad (if committed into a repository.). And that would be a bit of a problem to solve.

**Comment by Mr795** [comment]
that's why i didn't use a screenshot from the built wad and showed the unedited version instead.

**Comment by mc776** [comment]
> i think i would prefer less edited because you wouldn't need to find a way to not have an overlapped text in your title screen, which would like a jumbled up mess if it was made into a wad (if committed into a repository.). And that would be a bit of a problem to solve.

I'm talking about which of the two images here is better: https://github.com/freedoom/freedoom/pull/1224#issuecomment-1848769599

The original 320x200 images:
Screenshot_Doom_20231209_093609_edited
Screenshot_Doom_20231209_093609_editedalot

**Comment by Mr795** [comment]
in my opinion the graphical tweak is better.

**Comment by Mr795** [comment]
i decided to commit the graphical tweak.

**Comment by mc776** [comment]
Can you use this one?
Screenshot_Doom_20231209_093609_editedalot

**Review by mc776 — APPROVED** [review]

**Comment by mc776** [comment]
I just realized that the screenshot is from the same map as the first demo. Nice.

**Pull request merged**
