### PR TITLE
Make all skies vertically tile

### PR DESCRIPTION
**Pull request by kitchen-ace**

### CODE REVIEW

**Comment by kitchen-ace** [comment]
>Also, is it just me or the red skies are now less red (and more orange) after these changes?

I think it's just you :) Here are comparisons with just the raw graphics (left: original, right: my submission), I'll find some in-game screenshots shortly.

rsky1 rsky1v

rsky2 rsky2v

rsky3 rsky3v

sky3 sky3v

**Comment by kitchen-ace** [comment]
Here's a few in game shots, I think the first set, from the end of MAP11, is the only place in the Freedoom maps where the lack of tiling is noticeable. Nonetheless it's nice to have the others tile anyhow, IMO.

rDOOM0001 png
rDOOM0002 png
rDOOM0003 png
rDOOM0004 png

**Comment by kitchen-ace** [comment]
A few more with noclip

rDOOM0000 png
rDOOM0001 png
rDOOM0002 png
rDOOM0003 png

**Comment by Calinou** [comment]
I can see a difference in color in Firefox 77 on Fedora 31:

image

But not on Chromium 84 on the Fedora 31:

image

It's probably due to color profile handling in one or the other.

**Comment by kitchen-ace** [comment]
>I can see a difference in color in Firefox 77 on Fedora 31

Oh wow, that is quite the difference. To be safe, I've pushed an update that *I think* strips the colour profile from the images. Unfortunately no browser or image software I've tried displays them like in your Firefox 71 screenshot, so I can't be sure it looks as it should.

**Comment by Calinou** [comment]
@kitchen-ace That seems to do the trick, thanks!

**Comment by Xindage** [comment]
Hey i've noticed that you pngs are "raw" and yet not converted to freedoom pallete, should convert it on slade.

**Comment by Xindage** [comment]
decided to let build the wad and it works fine, them i got in game and used noclip to take ingame screenshots.
image
image
image
seems okay so far.

**Pull request merged**
