### PR TITLE
Texture updates.

### PR DESCRIPTION
**Pull request by Proluiz**
Reopened the changes whit a new branchs and updates probably my version of repo was outdated and it was bugging the merge, now its fine.

i added the 2 patchs fix mine and the blastfrog redwall, remenber to credit him for it.

### CODE REVIEW

**Comment by Proluiz** [comment]
Voros can you help me whit this check issue?

**Comment by Voros2** [comment]
You didn't edit textures.cfg

Look at the build log: 
E GR52 GIF: too short
make: *** [wads/freedm.wad]

**Comment by Proluiz** [comment]
wood patch is used only in a single texture, i'll try fix it in the way of you told me

**Comment by Proluiz** [comment]
acidental close...

**Comment by Proluiz** [comment]
nope making the patch 128x128 not work

**Comment by Voros2** [comment]
The same error keeps coming up:
E GR52 GIF: too short

Is there something wrong with the gif?

**Comment by Proluiz** [comment]
also about the the texture config:

A-WOOD1 128 128 (the textuze total size is 128x128)
    WOOD 0 0 (A patch wood is applyed at coordinates 0 0)
    WOOD 0 64 (A patch wood is applyed at coordinates 0 64)

i dont think of the poblem is on texture.cfg

actualy the 128x128 patch of this textures gets ouveylay by the other half (if you can uderstand me)

**Comment by Proluiz** [comment]
also he dont say who is the poblematic "GR52 GIF: too short"

**Comment by Proluiz** [comment]
no idea at all

**Comment by Voros2** [comment]
I'm gonna check out those three gifs in a few hours. See if there's anything wrong with them.

**Comment by Proluiz** [comment]
ok i'll let it on your hand i'll revest that test and i'll open you to be able to contribute in my fork

**Comment by Voros2** [comment]
Im fine with testing it my fork.

**Comment by fragglet** [comment]
These GIFs were written by "Chasys Draw IES" and apparently deutex can't handle the files for some reason. Can you reopen each in a different tool (eg. Gimp) and save them? That should fix the problem.

**Comment by Proluiz** [comment]
well rip chasys Draw heh

**Pull request closed without merging**
