### PR TITLE
Better GOR1 sprites

### PR DESCRIPTION
**Pull request by UltimateCraneo**
Better sprites for the twitching bloody hangedman !!!

### CODE REVIEW

**Comment by mc776** [comment]
Screenshots:
DOOM01
DOOM00

Stylistically it seems to fit the other artwork a good bit better, but can we get rid of the goofy white googly eyes on the face?

**Comment by UltimateCraneo** [comment]
The white eyes are meant to look dead, not like glasses, I would edit them out but idk how to use github too much, I'll see about it later maybe, wish I could just edit them easier cuz I had to delete my first attempt at submitting already cuz of issues with folders and naming, still tho, can be done, hopefully quicker too...

**Comment by mc776** [comment]
While seeing if I could get rid of the white eyes I made some edits to the C frame because the transition from B to C was looking a bit janky with the new detail:

gor1a0 gor1b0 gor1c0

Basically you can just drag the new files into the sprites folder and that should work.

**Comment by UltimateCraneo** [comment]
Here are the sprites with the white eyes removed, idk how to update the images on the pull, and don't really feel like deleting and reuploading it a third time so...

gor1c0
gor1a0
gor1b0

**Comment by UltimateCraneo** [comment]
> While seeing if I could get rid of the white eyes I made some edits to the C frame because the transition from B to C was looking a bit janky with the new detail:
> 
> gor1a0 gor1b0 gor1c0
> 
> Basically you can just drag the new files into the sprites folder and that should work.

ah just read your reply sorry didn't know you made one edit already

**Comment by UltimateCraneo** [comment]
(I hate github ngl whoever created this site's interface is a complete madman)

**Comment by mc776** [comment]
gor1a0 gor1b0 gor1c0

Did a few more tweaks to minimize the visible sections where the sprite looks identical between any two frames.

Besides this stuff I think the only difference between my edit and your edit is the dark bit on the face where the eyes used to be...

**Comment by UltimateCraneo** [comment]
ok but how do I submit those to replace the ones I already submitted via browser?

**Comment by selliott512** [comment]
> ok but how do I submit those to replace the ones I already submitted via browser?

The procedure for updating a file should be the same regardless of how the file was previously updated. If you wanted to do it from the command line it would probably be something like:
```
git commit -am 'Updated the file'
```
Or whatever you did in the web GUI before.

Later you, or someone, will likely squash the multiple commits into one.

**Comment by MerrittK** [comment]
Yeah, in general, with github, you don't edit things, you just post new things.
I think it would be better if the "face" area was shaded a bit darker, even if it doesn't have any detailing.

**Review by selliott512 — APPROVED** [review]
Looks good to me. I think the colors pop a bit more with this change, and the anatomy is better defined.

I'll approve it now, but maybe you can apply mc776's suggestion before once you figure out git. Feel free to ask about that though, if we can help, or if you'd like one of us to update your branch for you.

I can see the face and eyes being white to suggest decay, but I could also see darkening the face as per MerrittK's suggestion. I could go either way.

And finally, it's nice that you made it an indexed PNG with the correct Doom palette. And you kept the resolution the same.

**Comment by uhbooh** [comment]
Looks much better

**Comment by UltimateCraneo** [comment]
> if we can help, or if you'd like one of us to update your branch for you.

yes please lmao

**Comment by mc776** [comment]
How *do* you edit someone else's PR anyway?

**Comment by UltimateCraneo** [comment]
> How _do_ you edit someone else's PR anyway?

IDK !!!!!!!!

**Comment by UltimateCraneo** [comment]
BUT I JUST UPDATED !!!!!!

AND I DON'T EVEN KNOW HOW !!!!!!!!!!!!!

**Comment by UltimateCraneo** [comment]
Yes

**Pull request merged**
