### PR TITLE
New FreeDM endoom with info

### PR DESCRIPTION
**Pull request by Mr795**
i decided to make a new endoom for FreeDM wih information about freedoom.
[NewEndoomDM.zip](https://github.com/freedoom/freedoom/files/13453222/NewEndoomDM.zip)

### CODE REVIEW

**Review by mc776 — CHANGES_REQUESTED** [review]
Clipboard01
Not a huge fan of the logo... can I give it a try
[endm.zip](https://github.com/freedoom/freedoom/files/13454845/endm.zip)
Clipboard01

**Comment by mc776** [comment]
Slight update to add a bit more to the right edge of the "M"

[endm.zip](https://github.com/freedoom/freedoom/files/13461079/endm.zip)

**Comment by Mr795** [comment]
> Slight update to add a bit more to the right edge of the "M"  [endm.zip](https://github.com/freedoom/freedoom/files/13461079/endm.zip)

now that looks Much better than what i made.

**Comment by Mr795** [comment]
so do i just change the endoom i made to your edit of it?

**Review by mc776 — APPROVED** [review]

**Comment by mc776** [comment]
Approving this but leaving it open for a bit in case anyone's got anything to add or notices a typo.

**Comment by Mr795** [comment]
just checked for typos cause you said that, now its safe to say there is none.

**Comment by selliott512** [comment]
Looks good with some URL issues.

The main URL seems to be invalid due to the "www". It should be removed. Likewise with the main ENDOOM.

For the development builds the HTTPS URL has a certificate error that is avoided with HTTP. Ideally the certificate error should be fixed, and HTTP is marked "Not secure" anyway, so maybe it's ok to leave it.

**Comment by mc776** [comment]
Re: www, I think the best thing to do now is to merge this as-is, then post a new PR with both ENDOOM lumps fixed. I can do that tonight.

Re: https, how long has it been like that anyway? I thought it had been fixed and then broke again, but if there's no prospect of it being fixed then it should be changed.

**Comment by mc776** [comment]
On further reflection let's go with http since if the site were ever to be made https-only in the future it'll automatically redirect anyway.

**Comment by mc776** [comment]
These should do it:
[endooms.zip](https://github.com/freedoom/freedoom/files/13462652/endooms.zip)
freedm-sshot
freedoom-sshot
(I took the liberty of touching up the "F" and the "oo" a little)

**Comment by Mr795** [comment]
> These should do it: [endooms.zip](https://github.com/freedoom/freedoom/files/13462652/endooms.zip) freedm-sshot freedoom-sshot (I took the liberty of touching up the "F" and the "oo" a little)

ok, i guess ill update both endooms then

**Comment by Mr795** [comment]
also nice touchup to the freedoom one

**Review by selliott512 — APPROVED** [review]
Looks great.

**Pull request merged**
