### PR TITLE
build: add CREDITS-MUSIC.

### PR DESCRIPTION
**Pull request by mc776**

### CODE REVIEW

**Comment by mc776** [comment]
how do you do this help

**Comment by mc776** [comment]
It works now, would the character limit affect anything else?

**Comment by unithecutie** [comment]
Not that I know of.

**Review by selliott512 — APPROVED** [review]
I've approved this because it is a step in the right direction, and not harmful, but I think there is more to do. For all references to `CREDITS` in all files you probably want to add `CREDITS-MUSIC`:
```
git grep -w CREDITS
.gitignore:/CREDITS.txt
COPYING.adoc:CREDITS.
CREDITS:[See the CREDITS-MUSIC file for specific track authors and titles.]
CREDITS:D: buildcfg.txt, CREDITS, levels
CREDITS:D: buildcfg.txt, COMPILING.adoc, CREDITS, .gitattributes, .github, .gitignore, graphics, levels, lumps, patches, scripts, sprites
CREDITS:D: CREDITS-MUSIC
Makefile:CREDITS.txt: CREDITS
Makefile:CREDITS-MUSIC.txt: CREDITS-MUSIC
Makefile:TEXTDOCS=COPYING.txt CREDITS.txt CREDITS-MUSIC.txt
Makefile:	      ./COPYING.txt ./CREDITS.txt \
Makefile:	install -Dm 644 CREDITS NEWS.html README.html -t "$(target)$(docdir)/freedm"
Makefile:	install -Dm 644 CREDITS NEWS.html README.html \
Makefile:	      "$(target)$(docdir)/freedm/CREDITS"                               \
Makefile:	      "$(target)$(docdir)/freedoom/CREDITS"                             \
manual/manual-es.adoc:CREDITS.
manual/manual-fr.adoc:CREDITS.
manual/manual.adoc:CREDITS.
```

`make install` should install `CREDITS-MUSIC` and `make dist` should produce ZIP files that contain `CREDITS-MUSIC.txt`.

Somewhat related I'm curious if we'll ever want to have credits files for things other than music. Even less related I'm not sure how we want to distribute the non-English manuals. I'll try to remember to open an issue for that.

**Pull request merged**
