### PR TITLE
manual: Reduce number of table columns.

### PR DESCRIPTION
**Pull request by fragglet**
commit 89f918f5173b7 last year changed the manual to build as an A5 booklet. However, some of the tables now look very compressed with the smaller page width. We can make things look a lot nicer by reducing the number of columns:

* Weapons table: sprite column is eliminated (sprite is kept, but moved to the name column), and ammo column (moved to description column). This is a reduction from five columns to three in total.
* Special items table: name and description columns are merged. This is a reduction from three columns to two.
* Monsters table: name and description columns are merged. This is a reduction from three columns to two.

### CODE REVIEW

**Comment by fragglet** [comment]
Some comparison screenshots:

Weapons table before and after:
> Screenshot 2023-06-24 at 1 42 37 AM
> Screenshot 2023-06-24 at 1 42 43 AM

Special Items table:

> Screenshot 2023-06-24 at 1 42 53 AM
> Screenshot 2023-06-24 at 1 43 09 AM

Monsters table:

> Screenshot 2023-06-24 at 1 43 26 AM
> Screenshot 2023-06-24 at 1 43 17 AM

**Comment by mc776** [comment]
oh hell yes.

**Review by mc776 — APPROVED** [review]

**Comment by mc776** [comment]
I'd merge this with my newly acquired powers but I can't build it right this moment to be sure nothing glaring is missing...

**Comment by andOlga** [comment]
> I'd merge this with my newly acquired powers but I can't build it right this moment to be sure nothing glaring is missing...

You can download a build from the "Checks" tab of the PR, under "Artifacts".
The manual is built by the CI too.

**Comment by fragglet** [comment]
Built PDFs:

[freedoom-manual.pdf](https://github.com/freedoom/freedoom/files/11858286/freedoom-manual.pdf)
[freedoom-manual-es.pdf](https://github.com/freedoom/freedoom/files/11858285/freedoom-manual-es.pdf)

**Pull request merged**
