### PR TITLE
Edit to E1M1

### PR DESCRIPTION
**Pull request by shinobody**
New version of E1M1.
The map is now designed so it flows fine regardless if you first go down or to the right, starting room has some prison cell flavor (which fits the map name - Outer Prison - and the story of main character character being held captive by AGM and done experiments on), the big room with lowering pillars now has two extra ambushes to make combat more interesting - and also a ton of explosive barrels to teach a completely fresh player about that mechanic, the angle grinder secret has been reworked so it's easier for a player to kill the Pinkies with the grinder (previously this was really hard due to design of the area), there's more ammo and more health - since the very first map should probably not be too intense on resource management. Also some better signposting of way forward. Difficulty is toned way down on Easy modes.

### CODE REVIEW

**Comment by mc776** [comment]
This is a really interesting take but it needs work.

I won't rehash every point from that Discord conversation but I will say that it can really do well with a few more pairs of eyes working out some details with the lighting, textures and UI consistency.

It would be really nice if the player 1 start was a bit further to the right so you start off facing right down the middle of the door - it really gives a better sense of "the jail is broken and you're free" than being off centre like that.

Again, I really don't think spectres should be introduced in E1M1, as a variant of an existing stock type that should be introduced after the stock type has been established.

*Please* reconsider the use of those orange circle textures, especially now that the grey lava rock has been replaced with orange-brown dirt so there's a massive increase in warm colours in that area.

**Comment by selliott512** [comment]
I tend to be on the more conservative side of the spectrum with regard to map changes, so I would lean toward making small incremental changes instead of something this significant. That being said this looks nice.

Unfortunately it looks this was based on an older version of E1M1:
```none
~/git/freedoom-shinobody>git status -sb
## e1m1-changed...origin/e1m1-changed

~/git/freedoom-shinobody>git merge-base @ origin/master
52640d675033ddaba3667c60a4c6475984f38b3b

~/git/freedoom-shinobody>git log -1 52640d675033ddaba3667c60a4c6475984f38b3b
commit 52640d675033ddaba3667c60a4c6475984f38b3b (origin/master, origin/HEAD, master)
Merge: b155f84d e3c650a9
Author: Simon Howard <fraggle@soulsphere.org>
Date:   Fri Oct 23 15:13:41 2020 -0400

    Merge pull request #701 from MatthewTheGlutton/master
    
    SPOST0: fix X alignment.
```
Basically the above is saying that common ancestor with Freedoom's master branch is in October 2020.

It's helpful if the commit messages are descriptive. I almost took the liberty of doing it myself as a maintainer, but I thought it might cause more confusion than it would help since you may want to continue work. Any any case if you were to squash all three commits into one a commit message might be something like:
```none
levels: E1M1 various improvements

Various improvements to E1M1 including:
  * New prison like starting room.
  * Flow to the right or to the left.
  * More explosive barrels.
  * Grinder secret reworked.
  * More ammo.
  * More health.
```

**Comment by shinobody** [comment]
> I tend to be on the more conservative side of the spectrum with regard to map changes, so I would lean toward making small incremental changes instead of something this significant. That being said this looks nice.
> 
> Unfortunately it looks this was based on an older version of E1M1:
> 
> ```
> ~/git/freedoom-shinobody>git status -sb
> ## e1m1-changed...origin/e1m1-changed
> 
> ~/git/freedoom-shinobody>git merge-base @ origin/master
> 52640d675033ddaba3667c60a4c6475984f38b3b
> 
> ~/git/freedoom-shinobody>git log -1 52640d675033ddaba3667c60a4c6475984f38b3b
> commit 52640d675033ddaba3667c60a4c6475984f38b3b (origin/master, origin/HEAD, master)
> Merge: b155f84d e3c650a9
> Author: Simon Howard <fraggle@soulsphere.org>
> Date:   Fri Oct 23 15:13:41 2020 -0400
> 
>     Merge pull request #701 from MatthewTheGlutton/master
>     
>     SPOST0: fix X alignment.
> ```
> 
> Basically the above is saying that common ancestor with Freedoom's master branch is in October 2020.
> 
> It's helpful if the commit messages are descriptive. I almost took the liberty of doing it myself as a maintainer, but I thought it might cause more confusion than it would help since you may want to continue work. Any any case if you were to squash all three commits into one a commit message might be something like:
> 
> ```
> levels: E1M1 various improvements
> 
> Various improvements to E1M1 including:
>   * New prison like starting room.
>   * Flow to the right or to the left.
>   * More explosive barrels.
>   * Grinder secret reworked.
>   * More ammo.
>   * More health.
> ```

Thank you, sorry, I'm new to this. I will try to be clearer in messages next time.
The issue is I've been working on this edit for a while now and there's been another E1M1 edit in the meantime. I'm not sure how could I merge the changes between two 'forks' of a wad aside from implementing these changes manually? I did that with the fixes by captromancy from July 25 2021. Also just now I made a new version that also replaces AQTRIM03 with AQTRIM10, also tried to implement feedback by mc776.

However since mc776 submitted their own version of E1M1 just now, after discussion about this map in the Discord turned sour, I think we need to first figure out this situation instead of starting some edit war.

**Comment by mc776** [comment]
Fine, I'll rehash what was brought up in the Discord:
- Misaligned textures everywhere where the current map actually pays really close attention that sort of detail. I think I started mentally giving up at [this post](https://discord.com/channels/616148111076884520/692858629619056691/1056089471264759868) where you seemed to have no idea or (as your later comments suggested) willingness to care that the wall lines were cutting through the individual lights in the ceiling in that sector.
- Those awful orange circles everywhere. (To your credit you did remove that from the top of the starting room railing.)
- Retexture of outside rock area gets rid of that cool weird alien effect in favour of "brown shooter" genericness.
- Arbitrary monster closets that are literally just boxes added into the walls with no thought as to aesthetics.
- Sector lighting differences changed from subtle effects to extreme contrast with weird boundaries where the logic of the lighting is difficult to follow.
- Lots of little details added to the map geometry that don't add anything to the gameplay and take away from the austere aesthetics of the original.
- Lots of extra monsters that together with the new areas make the whole thing feel like a hasty edit to make the map harder for a quick co-op game, rather than the actual intro map to the beginning of the canon game.

Also:
- The railing breaks the flow for deathmatch.
- The starting area is just really, really visually busy now.

I'll give you this: it's a decent map to play as a PWAD. But E1M1 of the main game? The more I see what changed the less I'm willing to support it.

**Comment by shinobody** [comment]
Thank you for your input, but since I don't think it is fair and constructive critique so I think we will have to agree to disagree. You keep changing your feedback and making it more and more negative.
Primary goal of this edit isn't visual, the only real 'visual' edit was the prison part. Primary focus has been on streamlining gameplay - telegraphing progress, and ensuring that encounters are interesting regardless of where you go.

For example if you go to the lower/left path, you will end up having to shoot a ton of Imps/Serpentipedes with just the pistol in current vanilla E1M1. In fact there is so many that you can run out of ammo. So I lowered the count of Serps and added ammo. 
In that hall area that opens to the outside, the blue keycard indicator stripes were poorly visible. So I fixed them (something you also did in your version).
If player then goes through the door to the next room, they will immediately be in the line of fire of a zombieman and a shotgunner - and that is the introduction to the shotgunner. So I added a piece of cover, and put a medkit behind the cover so player will dive behind said cover.
 Then as you kill the shotgunner, he will drop a shotgun. Player will run to pick it up... straight to be seen by a pinkie, and now player will auto-select the shotgun.
 So we have a series of more interesting encounters than before, all rolled into a tutorial on two different enemy types, using cover and a new weapon, shotgun.

 The ambush in the barrel room is intended as the big 'setpiece' of the level, something cool and memorable about it. "Memorable levels are better than forgettable ones" is probably a non-controversial opinion. It's not there to make it particularly harder, and it's way toned down on Easy.

Also I changed the outside rock from black to brown for a simple reason - you're playing this on GZDoom. On Chocolate in 320 by 200, huge patches of this dark rock texture will blend together into visual black and grey noise, making it much harder to understand the structure of the rock outcroppings. And this is important, since player can walk inside a cave in these rocks.

Also I changed the gate-pillars in the barrel room so they no longer have water texture on top.

**Comment by mc776** [comment]
> the only real 'visual' edit was the prison part

Are you kidding!? You have made ***enormous*** changes *throughout the entire map*:
e1m1shinochanges

Every single one adds a huge amount more visual noise and distraction and is literally painful to look at compared to what it replaced.

The only one where the contrast was lowered was the outdoor area which just looks like a muddy pit where it used to be this impressive rock formation.

Many of them do not appear to have been previewed so that alignment issues could be checked. (That new "AGM" branding in the corner is particularly egregious, as well as the mismatched texture in the southern secret alcove)

There's a big shadow on the ceiling above the easternmost crate pile.

Everything about this edit just feels like someone thinking MORE MORE MORE without really improving what's already there.

**Comment by mc776** [comment]
> Also I changed the outside rock from black to brown for a simple reason - you're playing this on GZDoom. On Chocolate in 320 by 200, huge patches of this dark rock texture will blend together into visual black and grey noise, making it much harder to understand the structure of the rock outcroppings. And this is important, since player can walk inside a cave in these rocks.


I'll concede this: the actual passage looks better with the brown. But that area is completely optional and really should be considered (and tagged) as a secret.

I'm not sold on the other differences being improvements, especially given the proportions and visual balance and the fact that ingame there would be serpentipedes launching fireballs to let the player know there's something over there.

**Comment by mc776** [comment]
The way the starting railing, the "secret" cave wall, the monster ambush pattern and design around extreme micro-management of what the player is going to do all work towards making the player less free in a way that makes the whole jailbreak concept ring hollow.

**Comment by mc776** [comment]
Another example of the problems with this edit:


Original: seam between column and wall lines up with texture tiling.

Edit: whole new sector added to create this new detail, breaking the existing texture tiling in the process and also inexplicably using a logo texture that's also cut off - is this column supposed to rotate or something? It makes no sense.

**Comment by mc776** [comment]
As I said on the Discord and will summarize here, I just tried this map but with all the AQRUST08 in the starting area replaced with STARG textures like it is in the lower cell block.

I think I have a much better understanding of what you're trying to do with the texture changes.

The new enemies still seem to be a bit much for the first map but it does mean there's a much smaller difficulty spike between E1M1 and E1M2 (at least before your edit - I haven't tried how much harder you've made it if at all).

Raising all the sky ceilings back up to 536 vastly improves the appearance of the outdoor area, though the disappearing trees are still an issue:


Everything else I take issue with really is a question of fixing up details.

**Comment by shinobody** [comment]
Okay so we managed to succesfully talk it out with mc776 in the Discord, and instead of fighting, we're pooling our efforts. So the final version will be a collab edit - most visual changes by mc, most encounter design changes by me.

**Comment by shinobody** [comment]
Okay so this is the final version unless more feedback arises. This is a collab by me and mc776.
In fact, all changes in this new version were done by mc776, based on my work from previous commits.
image
image
image

**Pull request merged**
