### PR TITLE
levels: make secret armour unreachable fr/outside.

### LINKED ISSUE #1189: Freedoom Phase 2: Map issue
In Freedoom Phase2: Map 03, there is a secret item you can grab though the wall (at least using Crispy Doom 6.0) here is an attached screenshot of the area in question 
image

### PR DESCRIPTION
**Pull request by mc776**
Closes #1189.

### CODE REVIEW

**Comment by mc776** [comment]
Hey can we merge this now and I can just re-do the demo in #1217?

**Comment by mc776** [comment]
Or I can include a demo with this PR and hopefully #1217 gets merged first.

**Comment by selliott512** [comment]
This seems to have been fixed in the last commit (8b39bfe5efcb65c25b9a6be67caadfb8d3c2cb34) to MAP03 where the armor was moved away from the window. Can we close this?

**Comment by mc776** [comment]
Oops, had no idea how that Map03 even ended up on that PR...

**Pull request closed without merging**
