### PR TITLE
sprites: correct projectile offsets.

### PR DESCRIPTION
**Pull request by mc776**
Turns out #753 applies to all projectiles except the rocket pre-explosion frames.

(Yes, I am aware that this is how it's done in Doom. It's wrong there too and we're under no obligation to perpetuate that error.)

Also fixes a PLYC gibbing sprite copypaste error.

### CODE REVIEW

**Comment by Xindage** [comment]
could you post some screenshots for comparison?

**Comment by mc776** [comment]
Here's what they currently look like using [Nash's Radius Debug](https://forum.zdoom.org/viewtopic.php?f=105&t=60804
radebug_projectiles_before
)

Magenta shows where the collision box is. All monster fireballs and the plasma ball clearly extend far below the box, while the rocket extends a little above it.

BFG ball might be properly centered, it's hard to tell.

**Comment by mc776** [comment]
resizeafter
And here's after. Mancubus offset might need to be raised back up a bit...

**Comment by mc776** [comment]
Screenshot_Doom_20211102_183756

Here's what the mancubus ball looks like with the shift.

**Comment by mc776** [comment]
On further reflection maybe it's better to just center everything for now based on the canonical sizes - anything that gets that precise can probably just work around this anyway.

**Pull request merged**
