### PR TITLE
New MIDI

### PR DESCRIPTION
**Pull request by Voros2**
Replaces map09 and c3m8 with two of Blueworrior's tracks.

### CODE REVIEW

**Comment by Voros2** [comment]
Map29 MIDI added as both map07 and map29 use the same track.

MIDI created by Viscera Maelstrom.

**Comment by Voros2** [comment]
C1M3 and map13 shares the same track. Here's map13's midi, created by bytebeats.

**Comment by Voros2** [comment]
Why hasn't this been merged yet? The Travis build checks out fine.

**Comment by fragglet** [comment]
Looks good; this helps reduce the number of duplicate MIDIs. Thanks!

**Pull request merged**
