### PR TITLE
new title screen midis + older e3m1

### PR DESCRIPTION
**Pull request by KorpKat**
new title music, and bringing back the older e3m1 by blueworrior

### CODE REVIEW

**Review by mc776 — CHANGES_REQUESTED** [review]
Can we switch Phase 1 and Phase 2? The shorter track is almost perfectly timed for the 5-second title screen while it really sounds cut off with the longer track.

**Comment by mc776** [comment]
Leaving this recording here to show exactly where the track gets cut off by the demo transition:
[simplescreenrecorder-2023-10-10_10.22.32.ogg.zip](https://github.com/freedoom/freedoom/files/12860133/simplescreenrecorder-2023-10-10_10.22.32.ogg.zip)

**Comment by mc776** [comment]
If this gets merged before #1135 that PR can be updated for the credits, so I'll copypaste this here for future reference:

longer title is "Fight for Freedom" by Korp, based on ph-untitled.mid by Tyler "Picklehammer" Pantella
shorter title is "Horizon's Call" by Korp, based on "I Hate Fredrik Johansson" by Toby "Tobester" Collins Jr.

**Comment by KorpKat** [comment]
That's incorrect, Horizon's Call was not based on anything, it is entirely original.

**Comment by KorpKat** [comment]
And, i would prefer if [the shorter variant](https://cdn.discordapp.com/attachments/692859049921740831/1161486568117248051/PH1_-_Fight_for_Freedom_3.mid?ex=653879a9&is=652604a9&hm=90420c53351d4c7c6c7291f6fd784a8618492467cd6530eeb397f1c2789f0a08&) were added instead of the current one. I'm not really sure how to edit pull requests so ill leave it here and hope you or someone else could replace it.

**Review by mc776 — DISMISSED** [review]

**Comment by mc776** [comment]
Approved as-is for now but I'd like to ensure #1139 is merged first.

**Pull request closed without merging**
