### PR TITLE
patches: new bronze set by Korp

### PR DESCRIPTION
**Pull request by Talon1024**
I also re-did the rw25 series based on Korp's work

### CODE REVIEW

**Review by mc776 — CHANGES_REQUESTED** [review]
Looks great but I'm just a tiny bit concerned about the change to the cracked grey rock patch rw18s' tiling pattern - the seams are very, very visible:
seams
It tiles correctly but there's this clearly visible jump from one shade to another.

Could the shading be smoothed out a bit more so there isn't this jump in shade?

**Comment by Talon1024** [comment]
I'll remove the gray rocks for now.

**Review by mc776 — APPROVED** [review]

**Comment by fragglet** [comment]
The height of the top bar on the WALL02_* patches has shrunk a couple of pixels. Sometimes WADs make use of that alignment. It's not a huge deal but it might be preferable to keep the original height

**Comment by mc776** [comment]
For what it's worth, I'm running around E1M9 which uses this WALL02_* stuff a lot and the new update hasn't really affected anything noticeable:

DOOM05
DOOM04
DOOM03
DOOM02
DOOM01
DOOM00

**Pull request merged**
