### PR TITLE
Tweak speed/pitch of player death sounds

### PR DESCRIPTION
**Pull request by Ferk**
This is in response to #436
I'd rather the sounds are improved than removed, so I've shortened and tweaked them to make them less annoying. 

In the case of ``dspdiehi`` I added some short fade-out, removing part of the end, because it was getting distorted when sped up.

I don't have good recording equipment to completely remake them / make my own, so they are actually based on the same sounds, but I think this is a significant improvement.

Check it out and let me know if you think it should be edited further.

### CODE REVIEW

**Comment by AXDOOMER** [comment]
I removed the loud part from the first one and made the second one less noisy: https://ufile.io/d864f

I used your modified sounds.

**Comment by Voros2** [comment]
Are they 8bit, mono and 11025hz? I get noise after compiling with Deutex?

**Comment by AXDOOMER** [comment]
Maybe that's why I felt there was some noise in Ferk's sounds. I couldn't really improve them so I'm not going to redo the transformations that I did again. The sounds should be replaced with something that matches better with the FreedomGuy current voice.

**Comment by Ferk** [comment]
Ow, sorry. I've converted, built and tested the WAD in Retro Doom. When playing the WAV file in VLC there's a bit of noise (as was in the original) but there's no noticeable noise in-game.

To minimize the noise in the second sound (I mean ``dspdiehi``), I've just used some fading to shorten it without really affecting its speed/pitch.

Maybe it would be better to get new sounds from the ground up. But in the meantime I'd rather see them tweaked than removed, which was what #436 suggested.

**Comment by AXDOOMER** [comment]
@chungy The latest Freedoom didn't build: http://freedoom.soulsphere.org/

**Comment by Voros2** [comment]
Deutex was updated:D but the updates Deutex isn't in Freedoom's server.

You'll be happy to hear the tall sprite error has been fixed (mostly) and PNG support added.

**Comment by chungy** [comment]
Yup, we know. Build Freedoom yourself or wait for the server to be updated.

**Comment by AXDOOMER** [comment]
> You'll be happy to hear the tall sprite error has been fixed (mostly) 

Oh yes indeed. :smile:  Good job!

**Pull request merged**
