### PR TITLE
levels: add more deathmatch starts to Map27.

### PR DESCRIPTION
**Pull request by mc776**
Also create a door out of the berserk pack room.

Addresses #806.

### CODE REVIEW

**Comment by selliott512** [comment]
It looks like the Ubuntu build server had trouble pulling a dependency.

**Comment by mc776** [comment]
Do I need to re-do the entire PR? Since I need to make changes anyway it's fine though I should finalize the changes first.

Re: https://github.com/freedoom/freedoom/issues/806#issuecomment-1335267823

I can get rid of 3 DM starts but the door thing I don't understand at all - changing the special to 1 does not fix it and I have no idea why it only works in GZDoom but not in Chocolate.

**Comment by selliott512** [comment]
You should not have to re-do the entire PR. You can either add another commit with the newer version of `map27.wad`, or amend the commit with the newer version. I usually use git from command line, but I assume the web interface will allow you to upload the same file again (but I haven't tried it).

It looks like you have no tag (tag of 0) for the linedef in question. The sector tag is 4. It's like GZDoom is able to guess that you want it to apply to the sector behind it, but other ports are not.

**Comment by selliott512** [comment]
This may have been overlooked in the most recent batch of merges. We should get it in before the release. I don't normally merge level changes, but I can tomorrow if no one else does since this one has been approved, as far as I know.

**Comment by mc776** [comment]
Running a botmatch on Hideous Destructor instagib for a few minutes didn't bring up any obvious game-stopping stuck moments or offputtingly awkward starts.

I am unable to squash any commits on my end.

I don't have anything further to do on this so I think it's ready to go.

**Pull request merged**
