### PR TITLE
Improved player shooting sprites.

### PR DESCRIPTION
**Pull request by MatthewTheGlutton**
I haven't tested these ingame just yet, so I'm a little concerned about how they'll look together with the current running sprites.

If it's too much of a clash I'll stop trying to aim for this upcoming release, and keep working on the running and pain sprites and put up a PR with all of them at once.

### CODE REVIEW

**Comment by Calinou** [comment]
I find them better-looking than the previous ones, but I haven't tested them in-game either.

**Comment by MatthewTheGlutton** [comment]
I managed to get at least a chase cam view just now... I almost closed this PR after looking at it but it turns out the A/E transition when you start shooting is even worse with the current sprite than it is with the new one! (both of them are suddenly much thinner, more than can be adequately explained by the character blading his body to aim)

**Comment by chungy** [comment]
Please start using standard commit messages, see this page for details: https://chris.beams.io/posts/git-commit/

The last commit here is especially bad. The summary line tells nothing and the description is especially useless. If you aren't done with a change, don't commit it.

**Comment by MatthewTheGlutton** [comment]
I'll close this since I have no idea how to rebase or squash.

Point taken about the descriptions but I think I'll just email one of you the file next time...

**Pull request closed without merging**
