### PR TITLE
Update CREDITS

### PR DESCRIPTION
**Pull request by Anonysussy**

### CODE REVIEW

**Comment by mc776** [comment]
Can you update the same branch as you're using for the PR?

**Comment by Anonysussy** [comment]
I'm still pretty new to this, I just press edit in place button, my bad

**Comment by Anonysussy** [comment]
Screenshot_20231111_164757_Opera GXi don't think i can, it said that I don't have a write access to it and it told me to resort to a pull request

**Comment by mc776** [comment]
Edit this one https://github.com/Anonysussy/freedoom/blob/master/CREDITS

**Comment by mc776** [comment]
I see you've figured it out. Can you close this PR?

**Pull request closed without merging**
