### PR TITLE
patches: change colours/fix alignment of banners (rw16_1, rw16_2, rw16_3)

### PR DESCRIPTION
**Pull request by Richard-Stayman**
Removes the random purple pixel on all banners, and corrects the shading in the blue and green banners where dark red was used

### CODE REVIEW

**Comment by mc776** [comment]
I just noticed that the green isn't the correct palette and the circle things are off center. Might be worth fixing on this PR too...

**Comment by mc776** [comment]
Is it possible to run these through pngcrush or even export them from a finished iwad in slade or something? i'm pretty sure that 150% increase in file size is from unoptimized data.

**Review by mc776 — APPROVED** [review]

**Review by Xindage — APPROVED** [review]
good work

**Review by Xindage — CHANGES_REQUESTED** [review]
oh i haven't noticed it before, it's your first contribution, you should add yourself at the credits, please do another commit adding yourself on the CREDITS file.

**Comment by Richard-Stayman** [comment]
Done

**Review by Xindage — APPROVED** [review]
if you want to add extra details about yourself on future fell free to

**Pull request merged**
