### PR TITLE
DPstudio switchs, revision 2

### PR DESCRIPTION
**Pull request by Xindage**
Sorry for opening 2 PR, the problem is that I'm redoing my OS and things got break, please close the #706 on merge of this.

### CODE REVIEW

**Comment by rueter37** [comment]
I really like the new switches! But I noticed two oddities:
- The recent changes are not applied because of the filenames being uppercase. You still see the switches with the lights "leaking".
- On the recent variant of the switch with the red and green light, the switch handle always points down now. The older variant of the switch has the handle pointing up if the switch is set to green.

**Comment by Xindage** [comment]
Thanks i'll revise the commit.

**Comment by Xindage** [comment]
It's working as intended now.

**Comment by AXDOOMER** [comment]
Looks great!

**Pull request merged**
