### PR TITLE
New MIDI for E1M5

### PR DESCRIPTION
**Pull request by northivanastan**
I always found it kind of annoying that this same MIDI was used _four times_ in Phase 1; D_E1M5 and D_E2M6 are identical and both are reused in E4. So here's a new D_E1M5. The E1M5 map feels dark and empty to me, despite the relatively bright lighting in places, so I decided that my MIDI should emphasize that emptiness. 

Please do provide any feedback!

### CODE REVIEW

**Comment by northivanastan** [comment]
Looks like this would solve issue #499, someone else apparently had a MIDI for this but it was lost.

**Comment by northivanastan** [comment]
Also released the MIDI on [OpenGameArt](https://opengameart.org/content/derelict), for easier access.

**Comment by rueter37** [comment]
Really like this one, I fully support this being the track for E1M5.

**Comment by northivanastan** [comment]
Someone on Doomworld pointed out a technical issue with this MIDI - the drumset track is set to MIDI OutputPort 2, which will try to use a second MIDI driver preventing some users from hearing it. Help from MIDI wizards on this would be appreciated!

**Comment by northivanastan** [comment]
The same person on Doomworld (CammyBanana) fixed the MIDI, so thanks to them!

**Comment by Xindage** [comment]
Approved these changes.

**Pull request merged**
