### PR TITLE
New ENDOOM screen

### PR DESCRIPTION
**Pull request by Anonysussy**
This also comes with a slightly revised hand for the pistol sprites to get rid of some of the unnecessary edits i made back then.
image_2023-11-27_163440101

### CODE REVIEW

**Comment by Anonysussy** [comment]
Another slight edit to soften the ∞ a little bit

**Comment by mc776** [comment]
I thought the previous pistol edits were fine. What's the actual difference from your point of view?

**Comment by mc776** [comment]
Aesthetically I like the way the information is laid out in the current one better (and the cleaner lines of the border gives me a bit less eye strain) but the logo is definitely an improvement and the removal of everything the reader does not need to type into their browser from the URLs solves a few problems.

I do miss the symmetry of the current one though.

**Comment by mc776** [comment]
"...click anywhere in the window to quit" - not too sure about this one since you can actually run FD in DOS Doom now.

**Comment by mc776** [comment]
A suggested touchup:
[endoom-greyborders-centered.zip](https://github.com/freedoom/freedoom/files/13480538/endoom-greyborders-centered.zip)
Clipboard01

**Comment by Anonysussy** [comment]
I would suggest to use the green border instead to make things more sci-fi and futuristic-esque, it also helps with the monitor display

**Review by mc776 — CHANGES_REQUESTED** [review]
The edits in that previous pistol PR were, in fact, necessary.

Please revert the changes so this PR is for the ENDOOM only.

**Comment by mc776** [comment]
> I would suggest to use the green border instead, it helps with the monitor display I was going for, I'm away from my PC at the moment so I can't do much of an editing for now

Using the same colour text and border is never a good idea.

**Comment by Anonysussy** [comment]
> The edits in that previous pistol PR were, in fact, necessary.
> 
> Please revert the changes so this PR is for the ENDOOM only.

The edits I made is mostly reverting back the hand shading as my attempt at brighten the gloves for the 2nd hand backfires as it looks more garish than it needs to
Screenshot_20231128_133132_ibisPaint X
I chose to include them here so I don't need to make another PR for it which would make things more redundant

**Comment by Anonysussy** [comment]
> > I would suggest to use the green border instead, it helps with the monitor display I was going for, I'm away from my PC at the moment so I can't do much of an editing for now
> 
> Using the same colour text and border is never a good idea.

They meant to be monochromatic display, think of it like a fictional supercomputer in most films and you would probably get the idea, though I'm still thinking about other alternatives, so for the time being don't merge this one until further edits.

**Comment by Anonysussy** [comment]
image_2023-11-28_154853452
Any suggestion so far or should i go with your previous edit instead?

**Comment by selliott512** [comment]
I'm fine with the red and green squares. I do however feel that symmetry is important. The left and right text boxes should be the same sizes even if it means using text that is less clear. For example, they can just click on it if they are curious what "Daily" is. "Website" could probably be "Web". The lower text boxes could be vertically centered in their surrounding grey blocks. Small text fixes such as "ful" and "." and the end of sentences. Here's my attempt:

sle-endoom-attempt

That leaves two blank lines at the bottom. Maybe I should've added vertical space somewhere to expand it.

I can give this to you in usable form. Anyway, just some ideas for now.

**Comment by mc776** [comment]
Re: Anon's
Really not happy with all the unnecessary --=-=-=-==---=======s to be honest. Together with the green borders they make the text especially irritating to read. If you have objections to the content of the text itself, that you think it deserves to be obscured, let's address them that way instead.

I do like adding something in the middle though.


Re: SElliot's
I would have no idea what "Daily" means in that (Freedoom online daily quest? Daily featured map?) and the autobuilds page doesn't really explain what's going on either if you don't already know what it is.

> The lower text boxes could be vertically centered in their surrounding grey blocks. Small text fixes such as "ful" and "." and the end of sentences.

Not sure what you mean here? Every previous version posted here looked correct to me.

**Comment by mc776** [comment]
> The edits I made is mostly reverting back the hand shading as my attempt at brighten the gloves for the 2nd hand sorta backfires as it looks more garish than it needs to [...]
> I chose to include them here so I don't need to make another PR for it which would make things more redundant

If that's the only issue, I think it would be best to just shop that part of the darker sprite onto the current sprite and post those, because there's a bunch of other changes (offsets, asymmetrical lumpiness on the body of the gun itself) that had also been fixed which this PR would have reverted.

Sometimes it's good practice to put a bunch of related changes in a single PR, but (unless the ENDOOM had a pistol sprite that needed to be updated) there's nothing really conecting these two things so two separate PRs would be best in my view.

**Comment by selliott512** [comment]
> Re: SElliot's I would have no idea what "Daily" means in that (Freedoom online daily quest? Daily featured map?) and the autobuilds page doesn't really explain what's going on either if you don't already know what it is.

Maybe "Daily" wasn't the best choice. "Builds"? Anything short.

> > The lower text boxes could be vertically centered in their surrounding grey blocks. Small text fixes such as "ful" and "." and the end of sentences.
> 
> Not sure what you mean here? Every previous version posted here looked correct to me.

I may have confused myself with my own local edits. Please disregard.

**Comment by mc776** [comment]
> Anything short.

"Betas"? (but too many jokes - "if the regular release is too hard for you...")

"Devbuilds"?

(Personally, though, I like how the longer labels help fill out the visual space there without too much padding around the borders.)

**Comment by fabiangreffrath** [comment]
You could place the "Freedoom is ..." text right beneath the Freedoom logo, where it will only occupy two lines. The four shorter lines in the lower left box that become available may then hold the web links, e.g. 

```
Project Homepage:
 freedoom.github.io
Daily Builds:
 freedoom.soulsphere.org
```

**Comment by Anonysussy** [comment]
image_2023-11-29_205829324
the current progress so far, with some ideas from selliot and fabian thrown in

**Comment by mc776** [comment]
> You could place the "Freedoom is ..." text right beneath the Freedoom logo, where it will only occupy two lines. The four shorter lines in the lower left box that become available may then hold the web links

The current text was designed to be fitted into those specific boxes so some rephrasing might be in order if we do that:

[endoom-descontop.lmp.zip](https://github.com/freedoom/freedoom/files/13503109/endoom-descontop.lmp.zip)

**Comment by mc776** [comment]
My favourite proposal: go back to the "old" formatting method for the bottom text. Clean, simple, not an eternal struggle to force lopsided data into a symmetrical shape:

[endoom-oldbottom.lmp.zip](https://github.com/freedoom/freedoom/files/13503317/endoom-oldbottom.lmp.zip)

**Comment by selliott512** [comment]
> My favourite proposal: go back to the "old" formatting method for the bottom text. Clean, simple, not an eternal struggle to force lopsided data into a symmetrical shape:

I like it. One small question though, for the two horizontal lines that are above the website address the upper of the two of them does not extend to the edges of the screen. Did you mean to do that?

**Comment by mc776** [comment]
That was intentional - felt like a bit of negative space should be there instead of perfectly splitting off the logo. (Could even be a bit shorter in my opinion)

**Comment by selliott512** [comment]
> That was intentional - felt like a bit of negative space should be there instead of perfectly splitting off the logo. (Could even be a bit shorter in my opinion)

That's fine. I just thought I'd ask. I think it looks great.

**Comment by Anonysussy** [comment]
i would like these to be used instead, i also reworked the dev builds into a copyright info, imo i don't think the inclusion of dev builds is really that necessary, i also like the endoom to fill more of the empty space
Screenshot (692)
[endoom.zip](https://github.com/freedoom/freedoom/files/13514445/endoom.zip)

**Comment by mc776** [comment]
I've made some edits (fixed a typo on the last one I posted).


[endoom-oldbottom.lmp.zip](https://github.com/freedoom/freedoom/files/13530193/endoom-oldbottom.lmp.zip)

**Comment by mc776** [comment]
I did see it but I think it's best to go forward with this version.

**Review by mc776 — APPROVED** [review]

**Pull request merged**
