### PR TITLE
levels: made C1M2 vanilla compatible

### PR DESCRIPTION
**Pull request by andwj**
* Simplified lighting gradients in a few places, especially the
  numerous circles in the room to the E (large visplane overflows)

* Changed translucent glass window in S of map.

* Reworked the diagonal translucent window (near 434,-1364) and lowered
  the room on SE side to accommodate MIDGRATE texture.

* Replaced generalized linetype in backpack secret (in W of map).

* Lowered the corner area just past the broken sky room.  By chance this
  fixes the odd-looking stairs a bit further on.

* Made the translucent glass in SE of map simply be opaque (the player could
  not see much through it anyway).

* Changed doorway near (900, -1700) to look more like a doorway (it was
  previously looking too much like a window).

* Replaced translucent window just S of the broken sky room -- now solid
  (this window was high and player could not see much through it).

* For teleporting monsters into blue key room, replaced BOOM silent teleport
  linetype #269 with vanilla compatible #97 (vanilla has no silent ones).

* Replaced BOOM scroll linetype #85 with vanilla linetype #48.

* In blue key room, changed monster closet to use a vanilla linetype instead
  of a BOOM generalized one.  Also made closet have a lowering floor instead
  of a raising ceiling (to preserve the geometry there).

* Cleared a line with tag #7 and a BOOM generalized type, there was no matching sector.

* Replaced BOOM generalized type for switch just past red-keyed door,
  reworking the door so the lights do not get cut off.

* Fixed linedefs with missing textures.

* Large rework of the "blue room" -- can no longer use BOOM colormap fx,
  hence made all the walls, floors and ceilings use blue textures.

### CODE REVIEW

**Comment by chungy** [comment]
thanks

**Comment by fragglet** [comment]
Side note, please don't write #<number> in a commit or PR description unless referencing an issue - the tag numbers you've mentioned here have added irrelevant cross-references to several bugs.

**Comment by andwj** [comment]
On 12/28/15, Simon Howard <notifications@github.com> wrote:
> Side note, please don't write #<number> in a commit or PR description unless
> referencing an issue - the tag numbers you've mentioned here have added
> irrelevant cross-references to several bugs.

Obviously I would not have used # if I knew about this feature of github.

-- Andrew

**Comment by chungy** [comment]
I think the # symbol isn't too bad, just avoid using it in the future.

However, a more important stylistic thing: try to keep your description lines within 72 characters. Going over that seriously makes it look awkward in a `git show` or `git log` display.

**Comment by andwj** [comment]
On 12/29/15, Mike Swanson <notifications@github.com> wrote:
> However, a more important stylistic thing: try to keep your description
> lines within 72 characters. Going over that seriously makes it look awkward
> in a `git show` or `git log` display.

Ok, noted.

Cheers
-- Andrew

**Pull request merged**
