### PR TITLE
flats: remove pure black bit from FLAT1_1.

### PR DESCRIPTION
**Pull request by mc776**
flat1_1_oops

### CODE REVIEW

**Review by selliott512 — APPROVED** [review]
You indeed fixed the black pixels, but it looks like you made it a bit darker, particularly the brown regions, a change that persists after running both the before and after through deutex (it's a real change). I've approved it, but please check if you meant to do that.

**Comment by mc776** [comment]
Fixed.

**Comment by mc776** [comment]
And yes I did buld and run it this time:

Original
DOOM00

Built with my initial "fix" which might have gone bad after I'd run it through Irfanview and might have accidentally hit a gamma setting somewhere
DOOM01

Built with a re-do based on an extracted original flat from SLADE, done in Kolourpaint as usual
DOOM02

**Comment by ShovelCode** [comment]
Great.

**Comment by uhbooh** [comment]
Nice job

**Pull request merged**
