### PR TITLE
dehacked: C6TEXT fix

### PR DESCRIPTION
**Pull request by Voros2**
For some reason, C6TEXT doesn't display in the development IWAD. This fixes. Also changed a line to remove weirdness.

### CODE REVIEW

**Comment by chungy** [comment]
It seems to display fine in Chocolate, Crispy, PrBoom-Plus, and GZDoom to me. what port are you trying to test?

**Comment by Voros2** [comment]
It didn't display in PrBoom+ for me, but on Chocolate Doom it did. I'm not sure why. It would show Doom 2's C6TEXT rather than the one in the dehacked file. I edited the dehacked file and checked again by loading it in game, and it works now. Again, not sure while the repo IWAD wasn't showing it on PrBoom+.

**Comment by Voros2** [comment]
c6text
As you can see, C6TEXT didn't display.

**Comment by Voros2** [comment]
Along with the C6TEXT fix, I've also added sone fresh par times, for those hardcore players.

**Comment by chungy** [comment]
I'll take a couple of the transition text changes, but I really don't know why your copy of prboom-plus isn't working properly. Do you have an old version?

**Comment by Voros2** [comment]
It worked before until the last change with the backpack text. I use D-Touch's PrBoom+, so it's fairly new.

**Pull request closed without merging**
