### PR TITLE
Aquatex

### PR DESCRIPTION
**Pull request by Voros2**
This includes jmickle's Aquatex texture pack. I know this is a big decision, but over at the forums, this is what many are saying. Sodaholic/Blastfrog has also given a few screenshots of MAP02 retexturised with Aquatex, and it was well received. 

Here's what I did:
I did the math, and it does not exceed the vanilla lump limit.
I edited buildcfg.txt to include the flats.
I edited textures.cfg to include the patches.
All are named in lowercase letters.

I hope you merge this soon. Maps can then be retexturised with Aquatex.
:)

### CODE REVIEW

**Comment by Blastfrog** [comment]
I'm all in favor of this. Thanks for doing this work! :)

**Comment by Voros2** [comment]
^YES

**Comment by fragglet** [comment]
These are @jmickle66666666's, right? Can we add him to CREDITS please?

**Comment by jmickle66666666** [comment]
I'm already in there for music https://github.com/freedoom/freedoom/blob/master/CREDITS#L724
however i do request that my real name be removed, thanks

**Comment by fragglet** [comment]
Done.

**Comment by Voros2** [comment]
I'll credit him in another PR. Don't want this branch running into conflicts.
Is that ok with you?

**Comment by fragglet** [comment]
Okay, sure.

One last thing: several of the textures you're adding here appear to be multi-frame GIFs (ie. animated); see the Travis build log:

    w GR15 ./patches/aqsupp02.gif: other GIF images discarded
    w GR15 ./patches/aqsupp09.gif: other GIF images discarded
    w GR15 ./patches/aqtrim06.gif: other GIF images discarded
    w GR15 ./patches/aqtrim07.gif: other GIF images discarded

Can you fix this by flattening these down into single frame GIFs? Then I'll merge. Thanks

**Comment by Voros2** [comment]
Yeah i know about that. But Deutex only uses one of the frames and throws away the rest, so it shouldn't be a problem.

Right?

**Comment by Voros2** [comment]
But I'll do it in a few hours.

**Comment by Voros2** [comment]
Done

**Comment by Voros2** [comment]
How about replacing the current liquid flats with the Aquatex ones also?

**Comment by fragglet** [comment]
Merged - thanks.

**Pull request merged**
