### PR TITLE
Update old gore sprites

### PR DESCRIPTION
**Pull request by basedSkeleton**
Replace old gore sprites

### CODE REVIEW

**Comment by basedSkeleton** [comment]
I added two more sprites

**Comment by Xindage** [comment]
can you convert them in slade? right now they're really heavy comparated to the older ones (510%)

**Comment by basedSkeleton** [comment]
> can you convert them in slade? right now they're really heavy comparated to the older ones (510%)

Sure

**Comment by basedSkeleton** [comment]
Slade seems to only want to make them bigger in filesize and monochrome, no matter which way I convert them. I have a base resource selected and pallete selected, but slade still makes them monochrome and it won't show previews either. If you could convert them for me that would be great.

**Comment by Xindage** [comment]
what your name in discord?

**Comment by basedSkeleton** [comment]
> what your name in discord?
What do you want it for?

**Comment by selliott512** [comment]
Sometimes PNG software adds extraneous chunks to PNG files. Another common problem with PNGs in Freedoom is they are not indexed. I fixed the three PNGs in this merge request by copying them into the build, and then extracting the back out of the WADs produced using `deutex`. Here's what `gor2a0.png` looked like before this MR, after this MR and with my fix
```
%%% before-mr %%%
Offset Length Type      CRC Contents
     8     13 IHDR bac2383f 24x51 bdepth=8 ctype=3 comp=0 filter=0 inter=0
    33      4 gAMA 0bfc6105 0.4546
    49     32 cHRM 9cba513c white=0.313,0.329 red=0.640,0.330 green=0.300,0.60
    93     78 PLTE 5ec89782 00,ff,ff 2f,2f,2f 47,47,47 43,43,43 33,2b,13 77,5f
   183      1 tRNS 40e6d866 00 
   196      1 bKGD ec6eb588 19 
   209      7 tIME 84eae6dc 2017-2-21 18:49:49 GMT
   228    233 IDAT 078d1c18 38 cb 95 93 c1 52 c3 30 0c 44 dd 52 0a a4 a1 3c 
   473     37 tEXt 98bf8ca0 date:create|2017-02-21T18:49:49-08:00
   522     37 tEXt e9e2341c date:modify|2017-02-21T18:49:49-08:00
   571      0 IEND ae426082 

%%% after-mr %%%
Offset Length Type      CRC Contents
     8     13 IHDR f4519162 31x55 bdepth=8 ctype=6 comp=0 filter=0 inter=0
    33      9 pHYs 952b0e1b 3780x3780 1
    54     37 tEXt 98bf8ca0 date:create|2017-02-21T18:49:49-08:00
   103     37 tEXt e9e2341c date:modify|2017-02-21T18:49:49-08:00
   152   2428 IDAT 9a702f0e 58 85 c5 98 7f 68 1b e7 19 c7 3f f2 0e eb b0 8e 
  2592      0 IEND ae426082 

%%% selliott512-fix %%%
Offset Length Type      CRC Contents
     8     13 IHDR c38f6150 31x55 bdepth=8 ctype=3 comp=0 filter=0 inter=0
    33      8 grAb b52e8029 00 00 00 0c 00 00 00 53 
    53      1 sRGB aece1ce9 00 
    66    768 PLTE cee40d4a 00,00,00 1f,17,0b 17,0f,07 4b,4b,4b ff,ff,ff 1b,1b
   846    248 tRNS 28ceb637 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
  1106    894 IDAT 6e3d976a 38 8d a5 d4 4f 6f db 36 14 00 70 ff 81 14 23 18 
  2012      0 IEND ae426082 
```
The files are [here](https://selliott.org/tmp/freedoom/pr-803/). Feel free to copy them.

It seems that some of the increase in file size was due to you making the image more complex, which makes sense, but I also noticed that the three sprites used to have width 24, but now have three different widths. Is that ok?

**Comment by basedSkeleton** [comment]
Alright, I uploaded the converted versions into my pull request.
> It seems that some of the increase in file size was due to you making the image more complex, which makes sense, but I also noticed that the three sprites used to have width 24, but now have three different widths. Is that ok?
Yeah, that shouldn't be a problem ingame.

**Comment by selliott512** [comment]
Unfortunately it looks like the files are the same. It's [this directory](https://selliott.org/tmp/freedoom/pr-803/selliott512-fix/) that's needed. I should've been clearer.

I wanted to add a few details about the the PNG files in case it's interesting or helpful.

The original images, before this merge request, had a tiny palette with only the colors used by the image, which can be seen by the small 78 byte `PLTE` chunk. It makes it hard to edit the image and you probably noticed.

The image before my change was not indexed which you can see from the `ctype=6` and the absence of a `PLTE` chunk.

The images I've created (actually, that deutex created) are indexed with a 768 byte `PLTE`. It's the standard Doom palette.

Also, it's no big deal, but you have a lot of commit messages about deleting and adding files. If you like I can clean it up for you so you just have on commit with message, like the "Change the sprite to look like the new shotgunner" you wrote a while back.

**Comment by selliott512** [comment]
I can upload my copies of the images too and set you as the author of the commit, if that is helpful.

**Comment by selliott512** [comment]
I took the liberty as a maintainer of consolidating the commits into so you don't have a series of add and delete commits. I've also applied the files I mentioned. If you want to revert back to the way it was before my changes that would be commit `e2db25a708b36ceceff8e54fefce112327e7b98f`.

**Comment by Xindage** [comment]
Now the last steep is configurating the offsets in the build.cfg

**Comment by selliott512** [comment]
Here's before and after for the three modified sprites in game before any offset changes that Xindage mentioned:

gor-235-compare

**Comment by selliott512** [comment]
As to Xindage's comment about offsets, I think these are the three lines from `buildcfg.txt` that needed to be updated:
```
GOR2A0	12	83
GOR3A0	12	83
GOR5A0	12	51
```
The width used to be 24, so that seems clear. The first coordinate in the above should be half the width. Since all of the images used to be 24x51 the second coordinate is less clear to me.

**Comment by basedSkeleton** [comment]
> The width used to be 24, so that seems clear. The first coordinate in the above should be half the width. Since all of the images used to be 24x51 the second coordinate is less clear to me.

It's probably because these objects are meant to be placed hanging from the ceiling.

**Comment by Xindage** [comment]
this pr is still needing the rights offsets to be merged.

**Comment by selliott512** [comment]
I pushed my attempt at fixing the offsets:

pr-803-offset-fix

The three changed sprites are in the middle. I added two unrelated hanging gore sprites on the end for comparison. The X coordinate is half the image width. The Y coordinate was adjusted to get the tops of them to about the same height, and somewhere between the tops of the two guys on the ends.

I ran:
```
scripts/fix-gfx-offsets sprites/gor[235]a0.png
```
to verify that I had updated the `grAb` chunks correctly (it makes no difference because `buildcfg.txt` is sync with the PNGs).

**Pull request merged**
