### PR TITLE
musics: new music for dm27

### PR DESCRIPTION
**Pull request by Ospaggi**
new music for freedm

### CODE REVIEW

**Comment by Ospaggi** [comment]
oh no I forgot the label

**Comment by mc776** [comment]
Can you add `DM27: "Music for Freedoom 7" by Jeremy "Vandalorian" Emerson` to the "Previously featured" section? (Unless someone wants to have it replace something else... I can see it being used for one of the early Phase 2 cluster 3 levels but nothing in particular stands out)

**Comment by unithecutie** [comment]
Could this be moved to DM04 instead? The current DM27 track is a good one and @mc776 suggested replacing "Rush" in #1215.

**Comment by mc776** [comment]
> Could this be moved to DM04 instead? The current DM27 track is a good one and @mc776 suggested replacing "Rush" in #1215.
> 

I had totally forgotten about this and had to listen to "Rush" again to figure out what this was about

Yes I agree

**Comment by mc776** [comment]
Or, if Shells was specifically written for DM27, maybe we can move MFF7 to DM04?

**Comment by Ospaggi** [comment]
OK "Shells" going to  DM27 and "MFF7" to DM04

**Comment by mc776** [comment]
One last thing, can you add Vandalorian's last name back into the DM04 listing?

**Comment by Ospaggi** [comment]
I added it

**Comment by mc776** [comment]
And finally can you add to the "previously featured" section near the bottom:

```DM27: "Music for Freedoom 7" by Jeremy "Vandalorian" Emerson (moved to DM04, not removed)```

**Comment by Ospaggi** [comment]
ok! I added it

**Review by mc776 — APPROVED** [review]

**Pull request merged**
