### PR TITLE
level: map09

### PR DESCRIPTION
**Pull request by Voros2**
New map for Phase 2.

I am not the author of this map. To contact the author, email: sajber@sajber.info

This map was made specifically for Freedoom.

### CODE REVIEW

**Comment by fragglet** [comment]
Happy to merge, but if it's a new author can you please also update the CREDITS file?

**Comment by Voros2** [comment]
OK fraggle. I'll update it!

**Comment by fragglet** [comment]
Thanks - please bring branch up to date and I'll merge (can't merge now because of conflicts with CREDITS from the other update).

**Comment by fragglet** [comment]
Hey - I see you opened a new PR. For future reference, you should be able to just update the existing PR without needing to open a new one. Thanks :)

**Comment by fragglet** [comment]
Oh, I see you ran into conflicts. Fair enough then.

**Comment by Voros2** [comment]
I'm closing this now again, since the job is done.

**Pull request closed without merging**
