### PR TITLE
New patches

### PR DESCRIPTION
**Pull request by Voros2**
Two new TNT patches by uhbooh.

### CODE REVIEW

**Comment by Voros2** [comment]
Meant to be fix for two patches mentioned in https://github.com/freedoom/freedoom/issues/92

**Comment by Proluiz** [comment]
This pull request seens fine to be addeded into master.

**Comment by Voros2** [comment]
^yes it does. Two steps closer to fixing TNT patches.

**Comment by Voros2** [comment]
Added uhbooh's yellite2 patch.

**Comment by Voros2** [comment]
May i ask why this hasn't been merged yet?

**Comment by fragglet** [comment]
Is there a reason why disaster.gif uses the old (now replaced) Freedoom font?

**Comment by uhbooh** [comment]
I felt that it resembled the original texture better than the current font.

**Comment by Voros2** [comment]
I'm surprised uhbooh's patches weren't added. Is there problem with any of them?

**Pull request closed without merging**
