### PR TITLE
Make separate ENDOOM lumps for both Phases

### PR DESCRIPTION
**Pull request by MidwayMarine**
I would like to talk about the possibility of making separate, dedicated ENDOOM lumps for both Phases as they have been left untouched for 8 years without any changes, and I thought it would be a good idea to replace them with updated ones.
I uploaded these ones as possible candidates:

ENDOOMP1_PNGD
ENDOOMP2_PNGD

Feel free to edit and improve them.

### CODE REVIEW

**Comment by mc776** [comment]
Is a darker green available for the background?

**Comment by mc776** [comment]
...oh, right, that *is* dark green!

Could grey or red (with the green for a border or something) work? Having a darker background for the light text would be nice, especially if a player had just been playing a darker map.

**Comment by mc776** [comment]
In case anyone else has the ENDOOM screen disabled by default, here's the current for convenience of comparison:
fdend
It does seem a little weird for it to have just the name and URL and no explanation of anything like that... also are we moving away from branding it as two words these days?

**Comment by mc776** [comment]
At the risk of opening the floodgates I have one *tiny* wording suggestion:

"You have been playing ___"

The present perfect seems to work better than simple past to make it clear this playing is a very recent thing the aftermath of which the reader is still interacting with (in reading the ENDOOM screen itself).

**Comment by andOlga** [comment]
I actually prefer the current clean ENDOOM screen. To me the ideal change would just be to throw up our current logo on it (with the infinity symbol and all). But if we are to go through with these text screens, I'd like to *at least* throw some minor grammar corrections here.

For Phase 1:

> on Phase 1

Not 100% sure of this, but "in" Phase 1 reads a lot more sensibly to me.

> open-sourced

Should be "open-source", written the way you have it makes it seem like the project was closed-source at some point in the past.

> more over 30 maps

Should just be "over".

> counterpart

No, FreeDM is a *part* of the Freedoom project. "Counter"part implies it's some sort of separate thing.

> you will surely

This word sequence is used two times which makes it off-putting, perhaps replace the second instance with "definitely" or something.

> get satisfied

"be" satisfied.

> , get up and fragging!

I think this should be its own sentence. It has little connection to what comes before it.

For Phase 2:

> on Phase 2

Similar to the P1 complaint above, should be "in".

> Well, we hope you actually did that, ...

This is the mother of all run-on sentences, good god. Here's an attempt at making this readable...

> Well, we hope you actually did that, as AGM couldn't stop experimenting with all those aliens. We wouldn't even be here if it wasn't for you, the player that's reading this. You saved humankind, after all, even though you could have instead fragged your friends in FreeDM, the multiplayer part of the Freedoom project. Or you could have felt a little episodic and instead tried Freedoom: Phase 1, the first phase of the game.

The final part of this just feels weirdly condescending, the whole "you *could* have done those things, but you haven't, it's ok" is... weird. Kind of implies that Phase 2 is worse quality than Phase 1 or FreeDM, which it most certainly is not. I don't necessarily have a complete replacement for this paragraph off-hand, but I would suggest to write something less insulting there.

**Comment by MidwayMarine** [comment]
> ...oh, right, that _is_ dark green!
> 
> Could grey or red (with the green for a border or something) work? Having a darker background for the light text would be nice, especially if a player had just been playing a darker map.

I tried with red, but it looked more Id Software-like which we definitely don't want.
I tried with gray, looked like light mode which will definitely blind a lot of the players.
I suggest staying on green.
As for the other suggestion, I will try fixing them (unless someone else does) tomorrow.
ENDOOMP1_SUGGEST
ENDOOMP1_SUGGTWO

**Comment by mc776** [comment]
Dark grey and black could also work...

**Comment by MidwayMarine** [comment]
> Dark grey and black could also work...

There's no **dark** grey, the background palette only has **8 colors**.
Although black does have a **nice** color contrast feel, I think it would be kind of strange seeing text floating on your DOS prompt.

**Comment by MidwayMarine** [comment]
> At the risk of opening the floodgates I have one _tiny_ wording suggestion:
> 
> "You have been playing ___"
> 
> The present perfect seems to work better than simple past to make it clear this playing is a very recent thing the aftermath of which the reader is still interacting with (in reading the ENDOOM screen itself).

> > open-sourced
> 
> Should be "open-source", written the way you have it makes it seem like the project was closed-source at some point in the past.

I managed to do these two fixes, and thanks @andOlga for giving me some much needed issues with grammar, some parts have not really been cleaned out (I was busy with other stuff) while making these and i expect to fix them by tomorrow... Hopefully.

Here are the "not completely fixed" ENDOOM screens:
ENDOOMP1_PNGD
ENDOOMP2_PNGD

**Comment by mc776** [comment]
Or even better, get rid of that all-caps line and have

`You have been playing Phase ___ of the Freedoom project, a community-driven free and open source game for the Doom engine.`

also getting rid of the caps surrounding the word "Freedoom" since the actual name is just "Freedoom".

**Comment by MidwayMarine** [comment]
> First line doesn't quite catch the FOSS nature of Freedoom if you have the "free content"(??) and then the notoriously abused term "open source" without further clarification.
> 
> Might I suggest: `The Freedoom Project, a community-driven free and open source game for the Doom engine.`
> 
> And I think a black background with a dark (dithered?) green border would work best - I'm honestly having trouble trying to read that for more than a few seconds at a time.

Good idea, thinked about the black background for a moment, and I think it would be best if I did that (coupled with your green outline suggestion).
I will report back with an updated lump in some minutes (probably 10 or so).

**Comment by MidwayMarine** [comment]
Alright, I got @mc776's suggestion added and honestly, it feels really like a color contrast theme, and it's good.
Will commit the changes shortly.
ENDOOMP1_PNGD
ENDOOMP2_PNGD

**Comment by mc776** [comment]
What's wrong with my second suggestion? Or is that :/ react just because you only saw it after you'd made these latest changes?

**Comment by MidwayMarine** [comment]
> What's wrong with my second suggestion? Or is that :/ react just because you only saw it after you'd made these latest changes?

It's both of them. It's not really necessary to change it as I want it to feel more like Doom's ENDOOM lumps with their "YOU ARE PLAYING THE ULTIMATE DOOM" and it's line separating Id Soft from the upper corner, but if most of you want it the other side, sure, I will change it then 👍.

**Comment by mc776** [comment]
It's been a day and I'm looking at this with fresh eyes (and a less eye-hurting background).

Sorry, but I'm starting to agree with Olga's initial comments here. The chatty trying-to-sell-you-the-game talk feels inappropriate when we're not actually in need of selling any product, and the tone and diction now that I'm reading much closer kinda does to my brain what the green background was doing to my eyes.

This combined with the loss of the (honestly actually good) ANSI art of the current screen makes this at best a horizontal change rather than an improvement. It takes the one thing clearly lacking about the current and goes *way* too hard in the opposite direction, but at the expense of what was good about the current.

**Comment by MidwayMarine** [comment]
Well, it's okay, probably most people in here probably prefer the old ANSI art, so maybe we could work out something that includes the (updated) logo, coupled with some informative text (WADs to try out, trivia, and miscellaneous facts) rather than the trying-hard-to-sell-you-something-with-their-chatty-like-text from most games (Doom, Quake, Duke Nukem 3D) I originally implemented.

Hope this pull request wasn't way too much for you.

**Pull request closed without merging**
