### PR TITLE
add dependabot for github-actions

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

Thanks for your app. I add [dependabot](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide) for github-actions. I hope it is useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by Anonysussy** [comment]
> Thanks for your app.

The FD app had nothing to do with this project, you might want to check out for more info about the Android port: https://github.com/mkrupczak3/Freedoom-for-Android

**Comment by lavenderdotpet** [comment]
[](url)
SmartSelect_20241015_141921_Discord

**Comment by theavege** [comment]
Thanks for this project.
I don't know about [Freedoom-for-Android](https://github.com/mkrupczak3/Freedoom-for-Android)
I have play to Freedoom on Debian and I just want to help this project.
I cannot help your project more.

**Comment by Anonysussy** [comment]
> I have play to Freedoom on Debian and I just want to help this project.

when you mentioned Freedoom app i thought you mentioned the android port, the term just pretty common there, my mistake.

**Comment by lavenderdotpet** [comment]
> Thanks for this project.
> I don't know about [Freedoom-for-Android](https://github.com/mkrupczak3/Freedoom-for-Android)
> I have play to Freedoom on Debian and I just want to help this project.
> I cannot help your project more.

ah well this repo is essentially just assets 
u should look at adding that bot to the Chocolate doom or Crispy Doom GitHub

**Pull request closed without merging**
