### PR TITLE
Upload final SHELA0, SBOXA0

### PR DESCRIPTION
**Pull request by MatthewTheGlutton**
The commit that was intended to implement #604 ended up reverting the final edit to the box sprite.

Since I'm doing this I might as well upload the minor small pickup sprite edit too.

### CODE REVIEW

**Comment by selliott512** [comment]
I wish GitHub had a way of browsing images in the web interface. In any case, it looks like you added a row of pixels to the top of the shell box making the tops of the shells better defined, and you brightened up the yellow pixels in small shell sprite. Looks good to me.

**Comment by AXDOOMER** [comment]
Looks good.

**Comment by chungy** [comment]
Looks good to me too, I'll merge with a different commit message (more suitable)

**Comment by Ferk** [comment]
> I wish GitHub had a way of browsing images in the web interface.

Actually, it'd be relatively easy to add an adoc or md file that shows the sprites, linked directly from the sources. I think the manual already is doing that when introducing items (not for the monsters though, those are screenshots).

**Comment by Calinou** [comment]
You can click on the rich diff icon in the **Files changed** tab:

image

**Pull request closed without merging**
