### PR TITLE
patches: new stuff by Korp

### PR DESCRIPTION
**Pull request by Talon1024**
This is a draft because Korp also made a replacement for the gray rock wall, but it has some tiling issues/visible seams as mentioned in the previous PR #1097:
feamsrocks

### CODE REVIEW

**Comment by mc776** [comment]
Just for reference re: fraggle's comment on that other PR:
image

**Comment by mc776** [comment]
image
Leaving this here for reference before Discord's fog of time eats it - the WALL00 patches and WALL62_1 from id, side by side to show their similarity.

**Comment by mc776** [comment]
Seamless confirmed.

**Comment by mc776** [comment]
Is there anything else to add, or can this be merged?

**Review by mc776 — APPROVED** [review]

**Comment by Talon1024** [comment]
Nothing else to add right now. @KorpKat hasn't submitted any new graphics, and their wall00_{5,6,7,8} submissions (on the Discord server) don't look very good.

**Review by fragglet — APPROVED** [review]

**Pull request merged**
