### PR TITLE
Minor items by cwolf and raymoohawk

### PR DESCRIPTION
**Pull request by luckypunk**
https://www.doomworld.com/vb/post/1720049
Minus candle and candelabra (as requested by Voros)

### CODE REVIEW

**Comment by raymoohawk** [comment]
could you add the candelabra and candle?

**Comment by Voros2** [comment]
@raymoohawk IMO the candlebra looks nothing like a candlebra and the candle's color makes it hard to tell what it actually is.

**Comment by raymoohawk** [comment]
i made them into lamps to keep with the more technogothic theme of freedoom and because their lack of animations made them look strange in the original doom

the new candelabra replacement is more symmetrical than the current one in (which also does not look like a candelabra)
also the current candle is too brightly colored for something the will be always fully lit

**Comment by Voros2** [comment]
Huh. The pill like lamps don't look like lamps to me. If they were say quadrilateral shaped lamps, I might have believed it.

Even if the candle is too bright, this new one's color is too dark in tone if you ask me.

**Comment by raymoohawk** [comment]
i'll brighten the candle replacement, but at least add the lamp, it's better than the current one anyway

**Comment by Voros2** [comment]
Who am I to do anything, it's luckypunk's PR. If you feel like they are good, then so be it. You're the artist.

**Comment by Voros2** [comment]
BTW, luckypunk, I think you should revise this whole PR by submitting seperate entries in seperate commits.

**Comment by luckypunk** [comment]
@raymoohawk : I tried, but I'm not sure if it worked.

@Voros2 : 
> What's with the third commit "merge https://github..." and why two comits that are supposedly the same?
That's because I really don't know what I'm doing here.

**Comment by raymoohawk** [comment]
that's ok, i think i'll modify those two sprites some more

**Comment by Voros2** [comment]
Maybe, just maybe, you should close this PR, reupload each entry in seperate commits (eg sprites: arm2, sprites: fcan, etc) and in seperate branch (eg a branch named "sprites"). Then make PR with that branch, and I'm sure chungy won't have to do massive cleaning up for you.

**Comment by luckypunk** [comment]
@Voros2 : I'll look into it. I definitely won't learn how to do this tonight.

**Comment by Voros2** [comment]
'K. First amend all the commits you made here, possibly by reforking freedoom.

**Pull request closed without merging**
