### PR TITLE
New skull key indicators for doors

### PR DESCRIPTION
**Pull request by chexter10538**
Replaces generic human skulls with the unique ones

### CODE REVIEW

**Comment by mc776** [comment]
I can't see the previews...

**Comment by Xindage** [comment]
i cant see the previews too, something is wrong

**Comment by Talon1024** [comment]
You'll be able to see the previews if you view each file individually (... menu -> View File)

Here they are:
W108_2
W108_3
W108_4

**Comment by Xindage** [comment]
it changes what by what? i can see the new ones but i cant see the old one, can someone post me the differences so i can really look at them.

**Comment by Talon1024** [comment]
The old ones look like generic coloured skulls. These new ones look like the skull keys needed to open them.

The filenames should also be lowercased.

**Comment by slashdevslashurandom** [comment]
Looks like it'd be a good addition to my pull request #755... I wanted to do the same myself, but didn't want to mess up the graphics that already existed there (which looked like they were based on a photo of a skull)...

**Comment by selliott512** [comment]
I was curious how you added a file that should already exist, and it's because of the filename case issue mentioned above:
```
ls -lt patches | grep -i w108_
-rw-rw-r--. 1 sle sle  1092 May 13 07:23 W108_2.png
-rw-rw-r--. 1 sle sle  1103 May 13 07:23 W108_3.png
-rw-rw-r--. 1 sle sle  1129 May 13 07:23 W108_4.png
-rw-rw-r--. 1 sle sle  3671 Feb 13 13:15 w108_1.png
-rw-rw-r--. 1 sle sle   509 Feb 13 13:15 w108_2.png
-rw-rw-r--. 1 sle sle   526 Feb 13 13:15 w108_3.png
-rw-rw-r--. 1 sle sle   521 Feb 13 13:15 w108_4.png
```
The uppercase files are the proposed new files.

I think this is a good change, and it is in the spirit of #755 as slashdevslashurandom mentioned. To make this PR easier to apply I'd do the following to resolve the case issue, and make the commit more descriptive:
```
git reset --soft @~
mv -f patches/W108_2.png patches/w108_2.png
mv -f patches/W108_3.png patches/w108_3.png
mv -f patches/W108_4.png patches/w108_4.png
git commit -a --amend -F - <<EOF
patches: Colorblind friendly W108 skull patches

Update the W108 skull patches to make them like the skull keys added by
PR #755. This will be helpful to colorblind people.
EOF
git push --force
```

**Comment by mc776** [comment]
yeah those filenames should be lowercase

**Comment by selliott512** [comment]
I've taken the liberty as a maintainer to fix the filename case as per the suggested git commands in my comment nine days ago. If that bothers you can revert back to the way you had it. The three image files have not changed at all.

I also captured some screenshots in game (FD MAP11). 

Old:
old-keys-indicators

New:
new-keys-indicators

This PR should be ready to go.

**Comment by selliott512** [comment]
Ok, merged. I think merge commits are preferred, so that's what I did.

A git tip for future reference - in your fork if you create a branch for your pull request rather than using the "master" branch then your fork won't be tied up while you wait for your pull request to be approved.

Something that I noticed about the image files that I didn't think was worth delaying this request for - for the three PNG images the file sizes are a bit larger because they now include a 256 color palette rather than a more limited pallet:

```
Before this change:
$ ll $(</tmp/pngs)
-rw-rw-r--. 1 sle sle 509 May 22 16:07 patches/w108_2.png
-rw-rw-r--. 1 sle sle 526 May 22 16:07 patches/w108_3.png
-rw-rw-r--. 1 sle sle 521 May 22 16:07 patches/w108_4.png
$ identify $(</tmp/pngs)
patches/w108_2.png PNG 16x24 16x24+0+0 8-bit sRGB 21c 509B 0.000u 0:00.000
patches/w108_3.png PNG 16x24 16x24+0+0 8-bit sRGB 24c 526B 0.000u 0:00.000
patches/w108_4.png PNG 16x24 16x24+0+0 8-bit sRGB 20c 521B 0.000u 0:00.000

After this change:
$ ll $(</tmp/pngs)
-rw-rw-r--. 1 sle sle 1092 May 22 16:07 patches/w108_2.png
-rw-rw-r--. 1 sle sle 1103 May 22 16:07 patches/w108_3.png
-rw-rw-r--. 1 sle sle 1129 May 22 16:07 patches/w108_4.png
$ identify $(</tmp/pngs)
patches/w108_2.png PNG 16x24 16x24+0+0 8-bit sRGB 256c 1092B 0.000u 0:00.000
patches/w108_3.png PNG 16x24 16x24+0+0 8-bit sRGB 256c 1103B 0.000u 0:00.000
patches/w108_4.png PNG 16x24 16x24+0+0 8-bit sRGB 256c 1129B 0.000u 0:00.000
```
It's possible there should be some sort of cleanup where we go through all of the patches and reduce the color pallet size, possibly deleting unused colors, or just limiting to FD friendly colors, but no need to solve that problem right now.

**Comment by fragglet** [comment]
So one thing I noticed while looking at the screenshots in #755: each of the skull colors has distinctive horns and they actually point in the same directions that we're using for the keycard indicators (-, |, X):

shapes

... but the red and blue ones are reversed. It would be nice if the horns pointed in the same directions that the lines do - that would mean that we'd have a common language between the different key types. It should be possible to swap the color ranges for red and blue in the skull keys, status bar icons and corresponding textures. Not sure how much work that would be though. If we do this we can add a note to the manual explaining the system.

**Comment by fragglet** [comment]
Did some color range swaps for the red and blue skulls, WAD file is here with the changes if anyone wants to try them:

[skullswap.zip](https://github.com/freedoom/freedoom/files/8836004/skullswap.zip)

**Comment by slashdevslashurandom** [comment]
Looks good.

**Comment by mc776** [comment]
So will this be a new PR, or...?

**Pull request merged**
