### PR TITLE
Improvement to some Freedm maps

### PR DESCRIPTION
**Pull request by Proluiz**
Affecting dm01 02 03 04 06 this editiong make each map more unique and better themed.

DM01 - Major layout rework, now it look less Dwango still having the outside near the same, iternal parts was moved around, and bfg now is leaded by teleport, it make the player more vulnerable.

DM02 - Was mostly itemplacement fix, before the weapons was near all togheter making teamdm mostly frustating for who dominate that areas, the excess of things was removed and a new place was added to suit the rocketlauncher.

DM03 - Theme improvement, now it looks a more classic and brown, bfg was added and the secrets removed making the gameplay more fast and simple.

DM04 - Major rework, everything was changed, layout item placements and theme now it looks a heavy metallic base whit tech around whit green bricks, excess of itens was removed and everything is in diferent places except from plasma and spawn spots.

DM06 - Major rework, only a few of this map can be recognized, everything was changed to look like a "Something Egipty" making a heavy use of TNT textures, nothing to say about the changes since like i told EVERYTHING changed there.

### CODE REVIEW

**Comment by Voros2** [comment]
This needs to be merged soon.

**Comment by Voros2** [comment]
Sorry for the double post, but I think you should add the fix for map10's exit switch. Its misalligned.

**Comment by AXDOOMER** [comment]
> Sorry for the double post, but I think you should add the fix for map10's exit switch. Its misalligned.

Just comment in here: https://github.com/freedoom/freedoom/issues/238
People are doing as fast as they can.

**Comment by Proluiz** [comment]
i'm editing is same order of the maps is like 1 2 3 4 5 and etc, so soon i'll reach dm10 also dm05 is going to be replaced.

**Comment by AXDOOMER** [comment]
doom84

There's a tutti-frutti on map03.

**Comment by Proluiz** [comment]
ty for report, add on list to fix.

**Comment by Proluiz** [comment]
i'm thinking in keep it off and cancel this pull request and reopen it when the major rework be done, or i'll see something else, but for now give me a bit of time to think.

**Comment by Proluiz** [comment]
i'm thinking in keep it off and cancel this pull request and reopen it when the major rework be done, or i'll see something else, but for now give me a bit of time to think.

**Comment by Voros2** [comment]
That's probably a good idea if you intended to do something massive (which you are). By all means, close this PR and keep updating your fork with changes. When you're done, be sure to reopen this PR again!

**Comment by Proluiz** [comment]
on way ;)

**Pull request closed without merging**
