### PR TITLE
flats/patches/textures: add back old tentacles.

### PR DESCRIPTION
**Pull request by mc776**
They're good to have as an option.

Gratuitous screenshot of an edited E3M7 showing both:

### CODE REVIEW

**Comment by MerrittK** [comment]
Looks great, we can have the best of both worlds.

**Review by MerrittK — APPROVED** [review]
Looks great, we get the best of both worlds.

**Review by Rawmeatbober — APPROVED** [review]
👍

**Review by selliott512 — APPROVED** [review]
Looks good. I actually did try it in GZDoom. I had no issue adding these flats and textures in Eureka.

**Comment by selliott512** [comment]
tentacles

**Pull request merged**
