### PR TITLE
new endoom screen with info about freedoom and a disclaimer.

### PR DESCRIPTION
**Pull request by Mr795**
(not an rsd file anymore.), i made a wad for it in slade 3 and tested it in both the vanilla doom exe (provided i done it with dosbox 0.74-3) and chocolate doom 3.0.1, all worked pretty good.
[endoomv2.zip](https://github.com/freedoom/freedoom/files/13321843/endoomv2.zip)

### CODE REVIEW

**Comment by Mr795** [comment]
[endv2.zip](https://github.com/freedoom/freedoom/files/13313185/endv2.zip)
this is a zip that includes the wad file for it and a screenshot of it. also includes a version just in case the next major release is 1.0

**Comment by mc776** [comment]
I don't really have any opinions at all what should be in the ENDOOM so i can't say if this is an improvement or not.

In the meantime, can you make the file name all lowercase and give it a .lmp extension?

**Comment by mc776** [comment]
current
Had to refresh my memory as to what the current one was like.

I like how this swings in the exact opposite direction from the last time someone tried to add more text to this screen (#935).

I don't know how folks like the content of the text (see my initial reply), but the capitalization needs to be standardized (capitalize start of sentence, don't capitalize anything that isn't a proper noun - in this case that's just "Doom", "Freedoom" and "BSD Licence").

**Comment by Mr795** [comment]
> I don't really have any opinions at all what should be in the ENDOOM so i can't say if this is an improvement or not.
> 
> In the meantime, can you make the file name all lowercase and give it a .lmp extension?

ok, idk if just changing the extension will work. so i guess ill remake it in playscii because this one was done in an editor meant for wolfenstein 3D.

**Comment by mc776** [comment]
You should be able to just keep doing what you normally do, just rename the file when you upload it.

**Comment by Mr795** [comment]
alright i remade it in playscii and its now actually a lump file (.lmp)
[endoom.zip](https://github.com/freedoom/freedoom/files/13314476/endoom.zip)

**Comment by Mr795** [comment]
i replaced the endoom rsd with the endoom lmp in my fork.

**Comment by mc776** [comment]
:/

The monochrome now definitely feels like a downgrade from the ANSI art... the only information that couldn't be very quickly found by going to the web site is the summary of the BSD licence, and that is an issue with the website that could be addressed there too.

**Comment by Mr795** [comment]
> :/
> 
> The monochrome now definitely feels like a downgrade from the ANSI art... the only information that couldn't be very quickly found by going to the web site is the summary of the BSD licence, and that is an issue with the website that could be addressed there too.

yeah, i liked how it looked with the colors. btw i just tested it, its vanilla compatible. It has the same pixel size as the original endoom. (80x25px)

**Comment by Mr795** [comment]
> current Had to refresh my memory as to what the current one was like.
> 
> I like how the tone of this swings in the exact opposite direction from the last time someone tried to add more text to this screen (#935).
> 
> I don't know how folks like the content of the text (see my initial reply), but the capitalization needs to be standardized (capitalize start of sentence, don't capitalize anything that isn't a proper noun - in this case that's just "Doom", "Freedoom" and "BSD Licence").

That Endoom from #935 kinda looks similar to the original doom, is that fair use?

**Comment by mc776** [comment]
That was one of the reasons why it was not adopted, yes.

**Comment by Mr795** [comment]
> That was one of the reasons why it was not adopted, yes.

Oh ok. Btw I just realized my design for the e doom screen kinda takes the outline only as borders thing, I didn’t even know that. (It was further down the post)

**Comment by Mr795** [comment]
> > That was one of the reasons why it was not adopted, yes.
> 
> Oh ok. Btw I just realized my design for the endoom screen kinda takes the outline only as borders thing, I didn’t even know that. (It was further down the post)

**Comment by Mr795** [comment]
> > That was one of the reasons why it was not adopted, yes.
> 
> Oh ok. Btw I just realized my design for the endoom screen kinda takes the outline only as borders thing, I didn’t even know that. (It was further down the post)

I hid that because I accidentally quoted what I meant to edit.

**Comment by Mr795** [comment]
was it really necessary for me to add the version number?

**Comment by Mr795** [comment]
[endoomv2.zip](https://github.com/freedoom/freedoom/files/13321578/endoomv2.zip)
added more color and an abbreviated Freedoom on the left side of the screen that has the same (or almost the same) shading like the current endoom also every instance of the word "freedoom" is colored like the current endoom. (also the borders and most of the text is now red)

**Comment by Mr795** [comment]
> You should be able to just keep doing what you normally do, just rename the file when you upload it.

the endoom did need a bit of touching up, like having to use some other characters for the boxes some texts were in. (like to connect the boxes to the outer border of the endoom.

**Comment by mc776** [comment]
Screenshot of the latest version:
endoomv2

I might have some suggestions (pretty much all just related to whitespace) but I want to see at least one other person's approval in principle before I suggest any further action.

**Comment by selliott512** [comment]
The existing ASCII art is pretty neat, to be honest. Is this motivated by wanting to make the copyright more prominent?

**Comment by Mr795** [comment]
> The existing ASCII art is pretty neat, to be honest. Is this motivated by wanting to make the copyright more prominent?

It's because some people don't really read the text files that come in the zips.

**Comment by mc776** [comment]
> The existing ASCII art is pretty neat, to be honest. Is this motivated by wanting to make the copyright more prominent?

This was the second opinion I was looking for.

I think the underlying problem can be solved by adding one line in the current ENDOOM above the URL:
```
(C) 2021-2023. Released under BSD 3-clause licence. All rights reserved.
```

...and it's been so long I have no memory whether people normally do this with a big or little C...

**Comment by selliott512** [comment]
It feels like we aren't going forward with this in it's current form, but if we do what mc776 proposed 5 days ago it might be a good time to update the URL from "http" to "https" as we have elsewhere, but it doesn't matter much since it redirects anyway.

One concern about the proposed copyright line is we'll have to remember to update the year, but it should be pretty easy to update the last digit even with just a hexeditor (without any Doom tools). It could even be scripted, if we felt like it.

**Comment by Mr795** [comment]
> It feels like we aren't going forward with this in it's current form, but if we do what mc776 proposed 5 days ago it might be a good time to update the URL from "http" to "https" as we have elsewhere, but it doesn't matter much since it redirects anyway.
> 
> One concern about the proposed copyright line is we'll have to remember to update the year, but it should be pretty easy to update the last digit even with just a hexeditor (without any Doom tools). It could even be scripted, if we felt like it.

I think I might throw away some unnecessary clutter in the endoom to make it simpler in a bit
(Or just make a new endoom entirely. I don't know yet, I'll think about it.)

**Comment by Mr795** [comment]
I do think the 2001-2023 is gonna a bit of an unnecessary amount of yearly work to do without some kind of script that automatically does it.

**Comment by selliott512** [comment]
Maybe we can do such a script, but no hurry. For now we can either just hard code this as "2023", or maybe something like "current" so it doesn't have to be updated (I think we discussed that in Discord some point and presumably decided not to). My script to bump the version to 0.13.0 updates the copyright dates I'm aware of, so we should be covered for 0.13.0.

**Comment by Mr795** [comment]
i decided to just overhaul the endoom entirely. 
[end2.zip](https://github.com/freedoom/freedoom/files/13416209/end2.zip)
let me know if you like it or not, i'll not update my fork with this just in case you dont like it.

**Comment by Mr795** [comment]
screenshot here:
Screenshot 2023-11-20 11-31-21

**Comment by Calinou** [comment]
> One concern about the proposed copyright line is we'll have to remember to update the year, but it should be pretty easy to update the last digit even with just a hexeditor (without any Doom tools). It could even be scripted, if we felt like it.

`2001-current` should be just as valid: https://github.com/godotengine/godot/pull/70885

**Comment by Calinou** [comment]
I like the design, but the description text should probably be changed a bit. (Also, there's a typo; it should be "contributors" instead of "contributers".)

**Comment by selliott512** [comment]
Nice. I like how you this is closer to the Freedoom logo that appears on other screens. I'll have more feedback later today or tomorrow.

**Comment by Mr795** [comment]
> I like that design, but the description text should probably be changed a bit. (Also, there's a typo: it should be "contributors" instead of "contributers".)

oh, ill fix it there now

**Comment by Mr795** [comment]
> > I like that design, but the description text should probably be changed a bit. (Also, there's a typo: it should be "contributors" instead of "contributers".)
> 
> oh, ill fix it there now

thanks for letting me know by the way.

**Comment by Mr795** [comment]
typo fix:
[end2v2.zip](https://github.com/freedoom/freedoom/files/13418442/end2v2.zip)

**Comment by Mr795** [comment]
i might archive older versions of the endoom from this pull request. i dont know yet. (also i changed the endoom from a week ago in my fork to the current version made today)

**Comment by mc776** [comment]
Here's what it looks like now:
Clipboard01

Can I suggest a few changes:
* It's not self-evident what an autobuild is. Might say "Development builds can be downloaded here:", and move it all to the right where "All rights reserved" is now.

  * There's no real need to say "All rights reserved", it's implicit.

* "Contributors" is still misspelled.

* The text could be a bit more visually balanced (and not have a single word take up an entire line), and could describe Freedoom before launching into telling the reader what to do.

So with all these I suggest the three boxes read, respectively:

```
Freedoom is a free/libre project for the Doom engine,
made available under the BSD 3-clause licence.
```

```
For the full terms of the licence please see COPYING.txt.
For a full list of contributors, please see CREDITS.txt.
```

```
Development builds can be downloaded at https://freedoom.soulsphere.org/
```

**Comment by Mr795** [comment]
> Here's what it looks like now: Clipboard01
> 
> Can I suggest a few changes:
> 
> * It's not self-evident what an autobuild is. Might say "Development builds can be downloaded here:", and move it all to the right where "All rights reserved" is now.
>   
>   * There's no real need to say "All rights reserved", it's implicit.
> * "Contributors" is still misspelled.
> * The text could be a bit more visually balanced (and not have a single word take up an entire line), and could describe Freedoom before launching into telling the reader what to do.
> 
> So with all these I suggest the three boxes read, respectively:
> 
> ```
> Freedoom is a free/libre project for the Doom engine,
> made available under the BSD 3-clause licence.
> ```
> 
> ```
> For the full terms of the licence please see COPYING.txt.
> For a full list of contributors, please see CREDITS.txt.
> ```
> 
> ```
> Development builds can be downloaded at https://freedoom.soulsphere.org/
> ```

the typo is already fixed, its the version i put in my fork.

**Comment by Mr795** [comment]
> Here's what it looks like now: Clipboard01
> 
> Can I suggest a few changes:
> 
> * It's not self-evident what an autobuild is. Might say "Development builds can be downloaded here:", and move it all to the right where "All rights reserved" is now.
>   
>   * There's no real need to say "All rights reserved", it's implicit.
> * "Contributors" is still misspelled.
> * The text could be a bit more visually balanced (and not have a single word take up an entire line), and could describe Freedoom before launching into telling the reader what to do.
> 
> So with all these I suggest the three boxes read, respectively:
> 
> ```
> Freedoom is a free/libre project for the Doom engine,
> made available under the BSD 3-clause licence.
> ```
> 
> ```
> For the full terms of the licence please see COPYING.txt.
> For a full list of contributors, please see CREDITS.txt.
> ```
> 
> ```
> Development builds can be downloaded at https://freedoom.soulsphere.org/
> ```

alright, i updated the endoom with all your suggestions and replaced the endoom in my fork from yesterday with this version:
[end2v3.zip](https://github.com/freedoom/freedoom/files/13431427/end2v3.zip)

**Comment by Mr795** [comment]
btw i just didn't link the typo fixed version. it wasn't still like that

**Comment by mc776** [comment]
I've made a few adjustments, centering everything and making the important words (not "github!") stand out more:
Clipboard01
[ENDOOM.zip](https://github.com/freedoom/freedoom/files/13431859/ENDOOM.zip)

**Comment by Mr795** [comment]
> I've made a few adjustments, centering everything and making the important words (not "github!") stand out more: Clipboard01 [ENDOOM.zip](https://github.com/freedoom/freedoom/files/13431913/ENDOOM.zip)
> 
> The lines of text for ease of copypasting, in case stuff needs to be moved:
> 
> ```
> Freedoom is a free and libre game project for the Doom
> engine, made available under the BSD 3-clause licence.
> For the full terms of the licence, please see COPYING.txt.
> For the full list of contributors, please see CREDITS.txt.
> Development builds can be downloaded at https://freedoom.soulsphere.org/
> ```
> 
> EDIT: "For the" for both would make them identical in length.

made a wad out of it, if you wanna know the editer i use to make the endoom wads, its Slade 3.

**Comment by selliott512** [comment]
This last revision, which you seem to have agreed on, attached as `ENDOOM.zip` in comment 11 hours ago, looks great to me. Please add it as a commit and I'll approve it.

After that if you don't mind I may cleanup the git history so it's just one commit. It will still be the same change.

Wouldn't it be nice if we had a script to write the ENDOOM lump to the terminal so you could just do something like `make show-endoom` to see it? Probably not a high priority, but not difficult either.

**Comment by Mr795** [comment]
> Looks good. I took the liberty of applying `mc776edit.zip` that you both seem happy with, squashing the commits, and editing the commit message to be closer to the [50/72 standard that we sometimes follow](https://cbea.ms/git-commit/). The commit still has the same author (Mr795).
> 
> If you'd rather than I had not messed with your commit history and you'd like to restore it the commit prior to my edits was:
> 
> ```
> commit 361bc8d71541f1b8cb93fd99cc007224ec124265 (origin/master, origin/HEAD)
> Author: Mr795 <150305680+Mr795@users.noreply.github.com>
> Date:   Tue Nov 21 18:27:47 2023 -0330
> 
>     New endoom by Mr795
> ```

im completely fine with any edits to the commits.

**Pull request merged**
